### ISSUE TITLE
Purpose?

### ISSUE THREAD

**Issue by ASerbinski** [nextcloud/talk-desktop#1014]
Honest question, not a dig. I'm struggling to find any difference between this and just running it in a web browser. In fact, it looks to be just a web browser wrapper that limits the nextcloud installation to just the talk portion of it.

I was really hoping to see a more native IM application.

What do we actually gain by using this as opposed to a regular web browser?

**Comment by nickvergessen** [comment]
My top 3 are:

1. Running from system tray / running all the time, even when browser is closed
2. A separate window for organizing yourself
3. Better call notifications

For now the difference is rather limited, but you have the free choice.

**Comment by Fuseteam** [comment]
Additionally another small benefotis screensharing your nextcloud browser tab without needing to deal with the 'infinite hall' effect :D
