### ISSUE TITLE
Screensharing

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/talk-desktop#11]
Screensharing in Electron requires custom share dialog

**Comment by gbertolottiKS** [comment]
Hi.
Do you have some info about when it could be developed? Is it a work in progress?

For us is **the** missing feature of the app, which prevent us to use it.

Thanks in advance!

**Comment by nickvergessen** [comment]
It's still on the todo and mostlikely will be one of the next features that will be done for the desktop client

**Comment by jsddsfoh** [comment]
mobile also would be great for family members support! 👍

**Comment by gbertolottiKS** [comment]
Mmmmm, this is the repo for the desktop app.
The mobile apps already exist:
- android: https://play.google.com/store/apps/details?id=com.nextcloud.talk2
- ios: https://apps.apple.com/us/app/nextcloud-talk/id1296825574

**Comment by jsddsfoh** [comment]
Oh, I think I found my mistake: subscribed to this topic some time ago thinking at that time, it is about remote controlling. Now after reading again, I see it's about screen sharing. Sorry!

**Comment by Nimbusaro** [comment]
> Hi. Do you have some info about when it could be developed? Is it a work in progress?
> 
> For us is **the** missing feature of the app, which prevent us to use it.
> 
> Thanks in advance!

Same for us :)
We've been testing and loving Nextcloud for some months now (files), and now we're also trying to find an alternative to rocketchat whose basic community features (user status, read receipt, ...) are beeing moved to an expensive unecessary entreprise licence.

It is really cool to have this new talk dektop app (was really missing and the reason why we are not using Talk yet), it would be perfect with screen sharing (we can't really say our users "use desktop app for chat and visio, but use the web app if you need screen share").
Thanks for your work :)

Aurélien

**Comment by git529** [comment]
> > Hi. Do you have some info about when it could be developed? Is it a work in progress?
> > For us is **the** missing feature of the app, which prevent us to use it.
> > Thanks in advance!
> 
> Same for us :) We've been testing and loving Nextcloud for some months now (files), and now we're also trying to find an alternative to rocketchat whose basic community features (user status, read receipt, ...) are beeing moved to an expensive unecessary entreprise licence.
> 
> It is really cool to have this new talk dektop app (was really missing and the reason why we are not using Talk yet), it would be perfect with screen sharing (we can't really say our users "use desktop app for chat and visio, but use the web app if you need screen share"). Thanks for your work :)
> 
> Aurélien

Similar situation here.. We are considering switching over to Nextcloud for our company from our current solution, but the one thing stopping us is exactly this feature. Not being able to screen share on chat is a dealbreaker, and not worth migrating the file server/sharing etc.

Hopefully soon.. 

Thanks.

**Comment by ShGKme** [comment]
I'll work on it next week.

**Comment by lukas-holzner** [comment]
Have you made any progress? @ShGKme
