### ISSUE TITLE
The conversation does not exist upon clicking any conversation

### ISSUE THREAD

**Issue by plages** [nextcloud/talk-desktop#138]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open the Desktop app
2. Click existing conversation
3. Or create new one
4. then click it in the left hand column

### Expected behaviour
Conversation loads

### Actual behaviour
The conversation seems to load but then the screen goes black followed by "The conversation does not exist"
![2023_04_12_154016](https://user-images.githubusercontent.com/3436731/231478170-57def00d-bfcc-4d77-a92f-a8ab6770536a.gif)

## Desktop client

**Talk Desktop client version:** v0.3.0

**Operating system:** Windows 10 21H2

**Operating system version:** Windows 10 21H2

**Microphone available:** yes

**Camera available:** yes

## Server

**Nextcloud version:** 26.0.0

**Talk app version:**16.0.2

**Custom Signaling server configured:** no 

**Custom TURN server configured:** no

**Custom STUN server configured:** no

### Client log

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by ShGKme** [comment]
Thank you for your bag report. Technically, this is a duplication of #73 after the black screen resolving. I'm closing this issue, as the main discussion is in that issue.
