### ISSUE TITLE
User status in top bar is diverging

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-desktop#140]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Set a user status with icon

### Expected behaviour (also seen in web)
![Bildschirmfoto vom 2023-04-13 15-36-42](https://user-images.githubusercontent.com/213943/231776457-cf17100c-a495-476e-b5ab-4fe6c96e891f.png)

### Actual behaviour
![Bildschirmfoto vom 2023-04-13 15-36-47](https://user-images.githubusercontent.com/213943/231776440-8a423e46-5091-4030-9343-4198da27d66c.png)

## Desktop client

```
----------------------------System report----------------------------
Nextcloud Talk Desktop version 0.3.0
- Built with Nextcloud Talk version 16.0.2

Connected to:
- Server address: https://cloud.nextcloud.com
- Nextcloud Server version 26.0.0 RC3
- Nextcloud Talk version 16.0.0-rc.3

OS: Linux 5.19.0-38-generic (#39-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 17:33:16 UTC 2023)
----------------------------System report----------------------------
```

**Comment by fitus85** [comment]
Problem seems to be solved. Status is display correctly on Windows with Talk Desktop Release Version 0.19 und 0.20.

`----------------------------System report----------------------------
Nextcloud Talk Desktop version 0.20.0
- Built with Nextcloud Talk version 18.0.1

Connected to:
- Server address: xxxx
- Nextcloud Server version 27.1.5
- Nextcloud Talk version 17.1.4

OS: Windows_NT 10.0.22621 (Windows 10 Pro)
----------------------------System report----------------------------`

**Comment by ShGKme** [comment]
Solved in Talk
