### ISSUE TITLE
Linux Mint blank screen after entering conversation

### ISSUE THREAD

**Issue by Termalator** [nextcloud/talk-desktop#149]
The App starts but i am getting a blank screen after entering a conversation.

**Comment by wizdude** [comment]
Is this similar to the issue I just raised before #148 ?

**Comment by Termalator** [comment]
Yes, i am seeing the conversation for about a half second and then the screen is completely blank.

**Comment by ShGKme** [comment]
What version do you use?

Do you see a completely blank screen as mentioned in #73 reload to a chat view as mentioned in #138 ?

P.S. Please, do not remove the bag report template, especially the part with

```html
<!--- Please keep this note for other contributors -->
```

**Comment by Termalator** [comment]
Seems to be the same issue i am getting:

chromewebdata/:1 Not allowed to load local resource: file:///talk_window/#/apps/spreed/not-found
DevTools failed to load source map: Could not parse content for chrome-error://chromewebdata/preload.js.map: Unexpected end of JSON input

on the development console.

**Comment by ShGKme** [comment]
> Seems to be the same issue

Which one of these two?

Also, please try v0.3.1. There was a fix for a similar issue.

**Comment by Termalator** [comment]
https://github.com/nextcloud/talk-desktop/issues/73

**Comment by Termalator** [comment]
aah, i overseen that 0.3.1 seems to work now at first look :)

**Comment by Termalator** [comment]
As i said with 0.3.1 it seems to work fine

**Comment by Termalator** [comment]
Thank you and keep it going :)
