### ISSUE TITLE
black screen after entering a conversation

### ISSUE THREAD

**Issue by mokkin** [nextcloud/talk-desktop#150]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start Talk Desktop
2. Open an existing conversation
3. after half a second the screen is becoming completely black

### Expected behaviour
continue working on a regular screen with content

### Actual behaviour
![grafik](https://user-images.githubusercontent.com/2938748/232256380-afdb880d-7a5f-402e-b004-8fe0259bba3b.png)

![grafik](https://user-images.githubusercontent.com/2938748/232256387-ca7ac58b-2ad5-4224-9de5-0fcb0e488fa5.png)

## Desktop client

**Talk Desktop client version:** v0.3.0

**Operating system:** Ubuntu

**Operating system version:** 22.04

**Microphone available:** yes

**Camera available:** yes

## Server

**Nextcloud version:** 26.0.0

**Talk app version:** 16.0.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

### Client log

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by wizdude** [comment]
this sounds identical to the issue i raised #148

**Comment by ShGKme** [comment]
Thank you for your report. Please, provide a JavaScript log. You can find it in the console tab in development tools (open the context menu and click "Toggle Development Tools").

Also, please, try v0.3.1. It has a fix for a similar issue.

**Comment by mokkin** [comment]
Thanks for your feedback! Next time I'll  provide the console log.

Closing this as v0.3.1 fixed the issue.
