### ISSUE TITLE
Option to select audio output device

### ISSUE THREAD

**Issue by Termalator** [nextcloud/talk-desktop#160]
It would be nice to have not only the option to  select the sound input, but also the output device.
I know, that this is also not possible in the browser version, but it would make many things easier ;) .

P.s.: I am using Linux Mint, and don't if this is possible on other operating systems.

**Comment by ShGKme** [comment]
Closed as a duplication of: https://github.com/nextcloud/spreed/issues/7125

In this part Talk Desktop reuses Talk Web. There is no limitations to implement it in the Web client that could be solved by Desktop client.

Feel free to 👍 that issue :)

**Comment by Termalator** [comment]
Thank you :)
