### ISSUE TITLE
Cannot login with spaces in username

### ISSUE THREAD

**Issue by andyR14** [nextcloud/talk-desktop#199]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Login with "FirstName LastName" (space/blank between first and last name)
2. Return Message: Login was successful but something went wrong...
3. "One-Word-Usernamens" are working "Name"

### Actual behaviour
![talk](https://github.com/nextcloud/talk-desktop/assets/84279894/5ba7dc02-74a3-4669-8ad9-880cd29c5ce7)

## Desktop client

**Talk Desktop client version:** v0.6.0

**Operating system:** MacOS

**Operating system version:** macOS 13.4

## Server

**Nextcloud version:** 26.0.1

**Talk app version:** 16.0.3

**Comment by ShGKme** [comment]
Thank you for your issue, I'm looking on this.

**Comment by tobbeuchert** [comment]
The same issue appeared to me after installing the .flatpak file on Ubuntu 20.04.6 LTS. Since the issue was closed, what was the solution? Thank you!
