### ISSUE TITLE
Can I use Desktop Talk via 17.0.0beta with Nextcloud Talk 16.0.3

### ISSUE THREAD

**Issue by wizdude** [nextcloud/talk-desktop#200]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

this is a behavioural/operational query. apologies if there was a better place to ask this.

i have a Nextcloud 26.0.1 server with Nextcloud Talk 16.0.3.

i note that the latest Desktop Talk client contains code from 17.0.0beta.

should this combination work together? or should i be waiting until i go onto Nextcloud 27?

are there certain code combinations here that are recommended or ones that I should stay away from?

cheers, Wiz!!

**Comment by nickvergessen** [comment]
> should this combination work together?

Yes

> are there certain code combinations here that are recommended or ones that I should stay away from?

Newer Talk Desktop client should always work. Newer Talk server app version might be problematic and be blocked in the future, for now they work okay enough from our point of view.
