### ISSUE TITLE
Distribution strategy

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-desktop#257]
- [x] https://github.com/nextcloud/talk-desktop/issues/816
  - [ ] Windows
    - [x] #842
    - [ ] WIX MSI (add later if needed)
  - [x] Mac
    - [x] #843
  - [x] Linux
    - [x] #848
    - [x] ZIP as an universal option
    - [ ] Snap as a secondary Linux distributive
    - [ ] AppImage as a secondary Linux distributive
- [x] https://github.com/nextcloud/talk-desktop/issues/42

**Comment by sunjam** [comment]
I see Nextcloud desktop app available as:

- [Flatpak](https://docs.flatpak.org/en/latest/)
- [AppImage](https://docs.appimage.org/)

So, I think those would be open packaging standards that could be worth considering on the Linux side for the Talk desktop app.

**Comment by HomemadeAdvanced** [comment]
It would be great if winget would be supported.

**Comment by ShGKme** [comment]
> It would be great if winget would be supported.

I'll take care of it 🪟

**Comment by Fuseteam** [comment]
> I see Nextcloud desktop app available as:
> 
>     * [Flatpak](https://docs.flatpak.org/en/latest/)
> 
>     * [AppImage](https://docs.appimage.org/)
> 
> 
> So, I think those would be open packaging standards that could be worth considering on the Linux side for the Talk desktop app.

I would prefer a snap, as that in my experience that has the most seamless experience with updates (been using [nextcloud desktop as a snap](https://snapcraft.io/nextcloud-desktop-client))

**Comment by Fuseteam** [comment]
> Your Snap link indicates that this is packaged by a third party and not by the Nextcloud team.

so is the flatpak, only the appimage is officially distributed by the nextcloud team, that is beside the point of this issue tho ;)

**Comment by Areopagitics** [comment]
This App is absolutely awesome! The performance and features are better even than the official Signal flatpak I use often. 

I'm really looking forward to an official release.  I'm wondering if [Tauri](https://tauri.app/) would be a better a choice over Eletctron for a smaller, faster and easier way to distribute.

**Comment by ShGKme** [comment]
> I'm wondering if [Tauri](https://tauri.app/) would be a better a choice over Eletctron for a smaller, faster and easier way to distribute.

At least in the past, it wasn't possible. When we started, Tauri didn't have WebRTC support, which is critical for calls.

Also, Electron allowed a quick start. It was a known production-ready and simple solution. Especially when the app is mostly frontend, and frontend developers usually don't know Rust, which is almost never used in Nextcloud ecosystem.

Tauri also brings issues with cross-platform, as it uses the default web viewer. It means, even for Talk Desktop we have Safari issues on Mac.

But in general - yes, we consider the possibility of migrating to Tauri some where in the future. I look forward to Frontend tooling move to Rust, with [RSPack](https://rspack.dev) 1.0 release and coming soon [Rolldown](https://voidzero.dev/).

**Comment by pktiuk** [comment]
> > Your Snap link indicates that this is packaged by a third party and not by the Nextcloud team.
> 
> so is the flatpak, only the appimage is officially distributed by the nextcloud team, that is beside the point of this issue tho ;)

That's a shame there are no official Flatpak packages in FlatHub

**Comment by Fuseteam** [comment]
> That's a shame there are no official Flatpak packages in FlatHub
> 
> Maybe this should be added to 1.0 roadmap? [#635](https://github.com/nextcloud/talk-desktop/issues/635)

you do realize that's part of https://github.com/nextcloud/talk-desktop/issues/816, right? which is already on the roadmap, given it's a preview and all

**Comment by Areopagitics** [comment]
> > I'm wondering if [Tauri](https://tauri.app/) would be a better a choice over Eletctron for a smaller, faster and easier way to distribute.
> 
> At least in the past, it wasn't possible. When we started, Tauri didn't have WebRTC support, which is critical for calls.
> 
> Also, Electron allowed a quick start. It was a known production-ready and simple solution. Especially when the app is mostly frontend, and frontend developers usually don't know Rust, which is almost never used in Nextcloud ecosystem.
> 
> Tauri also brings issues with cross-platform, as it uses the default web viewer. It means, even for Talk Desktop we have Safari issues on Mac.
> 
> But in general - yes, we consider the possibility of migrating to Tauri some where in the future. I look forward to Frontend tooling move to Rust, with [RSPack](https://rspack.dev) 1.0 release and coming soon [Rolldown](https://voidzero.dev/).

Thank you for the update!  I'm sure the rust tooling will make the binary distribution easier especially with [cargo-bundle](https://github.com/burtonageo/cargo-bundle) / or the new kid [cargo-packager](https://github.com/crabnebula-dev/cargo-packager)

**Comment by LeSpocky** [comment]
Would it be possible to have good old Debian packages, or maybe even get this into the actual Debian packaging system so it can be installed through *apt* as usual?

**Comment by schiessle** [comment]
Are there plans to publish the flatpak at flathub?

I think this would be really nice because it would enable auto-updates via the package manager of most distributions.

**Comment by nickvergessen** [comment]
As soon as we finished the signing work for other distros we can have a look

**Comment by ShGKme** [comment]
> Are there plans to publish the flatpak at flathub?

Yes, if we go with Flatpak

**Comment by ShGKme** [comment]
Auto-update and adding checksums are moved to separate issues. Closing for now.

Additional distribution might be discussed in separate issues.
