### ISSUE TITLE
Notifications: add popup window for a call notification with join/decline buttons

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/talk-desktop#292]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

In contrast to a text message, a call notification often needs an immediate reaction to join a call.

**Describe the solution you'd like**

Add a pop-up window with a call notification with two buttons:
- "Join" - opens the talk window, opens the chat, joins the call
- "Decline" - closes the popup

**Describe alternatives you've considered**

Use native notifications. Make a call native notification always shown and add buttons to the notification.
It is definitely possible on Windows, but I'm not sure it is possible on MacOS and all the Linux desktop environments.

**Additional context**

We have it on both Android and iOS mobile clients. See also:

**Comment by DorraJaouad** [comment]
Is it shown when Talk desktop is minimized and/or when it is expanded ?

**Comment by nickvergessen** [comment]
Both
