### ISSUE TITLE
chage avatar for created conversation

### ISSUE THREAD

**Issue by marian790** [nextcloud/talk-desktop#293]
Pleas add option to change avatar for created conversation.
![talkavatar](https://github.com/nextcloud/talk-desktop/assets/60311864/19540d45-dc47-4cde-b414-743700cdcc10)

**Comment by Antreesy** [comment]
Hello, @marian790!

![image](https://github.com/nextcloud/talk-desktop/assets/93392545/4124f2fe-e72e-4838-b1fc-b9848f7e771a)
This option is available on all clients since Nextcloud v 27.0. Which version are you currently using?

**Comment by marian790** [comment]
v26, snap install....so...
