### ISSUE TITLE
Application does not run on Windows Server 2012R2

### ISSUE THREAD

**Issue by irfancyp** [nextcloud/talk-desktop#307]
On our environment we have few Windows Server 2012R2 but when you start exe below error occurs and application does not start
I believe it would be very nice to have backward combability too

"The Procedure entry point DiscardVirtualMemory could not be located in the dynamic link library C:\Nextcloud.Talk\Nextcloud Talk.exe"

**Comment by nickvergessen** [comment]
The app is not supposed to run on a server but should run on the actual user's computers.
Also 2012 is way too old and will not be supported.
