### ISSUE TITLE
System tray icon should change color (may be become red) when there is an unread message.

### ISSUE THREAD

**Issue by irfancyp** [nextcloud/talk-desktop#350]
I have noticed that I am forgetting to reply some chats when I tend to delay the response to few hours later. it's very easy to clear all notifications from action center with one button accidentally but if we had an updated system tray icon for talk events event after we missed the initial notification (from action center) we will always know that there is still an unread message.

**Comment by ShGKme** [comment]
Duplication of https://github.com/nextcloud/talk-desktop/issues/291
