### ISSUE TITLE
no win32 binary for v0.12.0 ?

### ISSUE THREAD

**Issue by Refhi** [nextcloud/talk-desktop#362]
Unfortunatly I can't find the win32 asset for the lastest release on https://github.com/nextcloud-releases/talk-desktop/releases/tag/v0.12.0 am I looking at the wrong place ?

Thanks a lot for your work on talk-desktop !

**Comment by nickvergessen** [comment]
I can not build it myself. It usually is done by another college. Should be there later today or tomorrow.

**Comment by ShGKme** [comment]
@Refhi Windows x64 Package is ready, you can download it from https://github.com/nextcloud-releases/talk-desktop/releases/tag/v0.12.0
