### ISSUE TITLE
The language is in English instead of German

### ISSUE THREAD

**Issue by Dtrieb** [nextcloud/talk-desktop#363]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

If I start NC Talk Desktop it is in English but, I want to use it in german.

**Comment by ShGKme** [comment]
The problem with translating these windows is resolved.

You can now add translations on Transifex:
https://app.transifex.com/nextcloud/nextcloud/translate/#de/talk_desktop/454589186

It might be added to the beta.2 release the next week.
