### ISSUE TITLE
Monochrome icon

### ISSUE THREAD

**Issue by Plugrol** [nextcloud/talk-desktop#364]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Problem*
I'm always frustrated when I see my Systemtray as all icons are monochrome except this one

**Solution**
I would want a setting to make the icon monochrome by removing the blue background. You can see the current icon on the image below:

![image](https://github.com/nextcloud/talk-desktop/assets/53694440/df6f22f1-dec0-4889-a1e3-3be48ccde379)

**Comment by ShGKme** [comment]
Depends on: https://github.com/nextcloud/talk-desktop/issues/27

**Comment by ShGKme** [comment]
- Fixed by [#836](https://github.com/nextcloud/talk-desktop/pull/836)
