### ISSUE TITLE
Windows push notification service is not working with the talk app

### ISSUE THREAD

**Issue by irfancyp** [nextcloud/talk-desktop#368]
We have an environment of virtual machines where several end users login to same windows server 2019 machine. Talk desktop client works fine but does not send any notification to action center thus nobody understands if they received any new messages and i assume the reason is current notification procedure of talk application is not using windows push notification api. If it did use wns api talk application would be listed under windows settings allow notifications from these senders list. I believe this issue should be fixed or updated accordingly as talk client is meant for windows users

**Comment by ShGKme** [comment]
We use Notification API from Electron's Chromium, which uses Windows Notification API (at least notifications are shown as native and displayed in the notifications side bar.

Are you sure that this is not a problem with notifications in general? Do you have local notifications?

**Comment by irfancyp** [comment]
I can confirm that this isse does not exist in windows 10 but in windows server 2019 its does exists. I can also confirm that we receive action center notifications from various apps with no problem like edge browser, windows defender, ms outlook and even 3rd party apps like PopTraU (Imap notifier app). I dont have enough knowledge to point you what is exactly wrong, but I am sure that current method of push service is not windows native enough. I also would like to mention that while I was searching internet for possible fix, I came across with an article which seems to me like a potential solution for the current issue. 

https://devblogs.microsoft.com/ise/2016/10/30/showing-native-windows-notifications-from-electron-using-nodert/

**Comment by nickvergessen** [comment]
If Windows 7/10/11 works that's good enough for us.

Windows **Server** is jot a target OS for a **Desktop** Client

**Comment by TheMatzy** [comment]
Isn't a terminal server with Windows 2019 a target OS for desktop clients?

**Comment by himself1985** [comment]
Same Problem here with Windows Server 2019 in RDS environment. Windows 10 works fine. It would be nice if you can fix that.

**Comment by himself1985** [comment]
Is this planned for version 1.0?
