### ISSUE TITLE
Simplification of the Design: Too many Title Bars?

### ISSUE THREAD

**Issue by louim-lbs** [nextcloud/talk-desktop#377]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
- Currently, the desktop chat application includes a standard title bar at the top of the window, which displays the application name and provides window management options (e.g., minimize, maximize, close buttons).
- Also, there is the web-like main bar with a big "Nextcloud Talk preview", search, notification and self-menu icons.
- Finally, there is the conversation-specific bar (conversation settings, start call button...).

I don't know exactly why, but I find the combinaison of three bars being weird and overwhelming...
Also, there is too much corporate text in my opinion.

Maybe we could have an option to hide or make this three bars more integrated to provide a cleaner and more streamlined user experience. For enhanced aesthetic and modern design.

**Describe the solution you'd like**
An option within the application's settings or preferences menu that allows users to toggle the visibility of the title bars on or off. This way, users who prefer the traditional window layout with the title bar can keep it, while those who prefer a more streamlined interface can choose to hide it.
I don't see a perfect solution here, but maybe some ideas will emerge from the discussion.

**Describe alternatives you've considered**

Current Talk:
![image](https://github.com/nextcloud/talk-desktop/assets/82395416/7c3f08cc-8356-47a2-a91f-17bab42fb153)

Some options from Messenger, WhatsApp, Telegram and Signal:
Corporate titles or icons are very small, and they only have two bars. 
Messenger:
![image](https://github.com/nextcloud/talk-desktop/assets/82395416/313bcae3-23c9-4bfc-b9e3-939fb94af0c9)

WhatsApp:
![image](https://github.com/nextcloud/talk-desktop/assets/82395416/3daca19f-6da3-4952-b962-62cb449f94b3)

Telegram:
![image](https://github.com/nextcloud/talk-desktop/assets/82395416/3d74c3b7-e99a-4100-819d-95e91b5c6858)

Signal:
![image](https://github.com/nextcloud/talk-desktop/assets/82395416/e38c0fbe-146d-45fc-b815-2d9c2c9a37ac)

**Additional context**
It's an open suggestion!

**Comment by ShGKme** [comment]
Yep, this is in a plan. I have some drafts.
