### ISSUE TITLE
self signed certificate in local network does not allow the use of the app

### ISSUE THREAD

**Issue by Cate95** [nextcloud/talk-desktop#385]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
Dear Devs,

First of all thanks for the development of this tool.

**Is your feature request related to a problem? Please describe.**
The Problem ist that I cannot use the nextcloud talk desktop client neither on linux (endeavouros/arch) or windows since I have a self signed certificate from true nas scale.

**Describe the solution you'd like**
In other nextcloud dekstop client apps, one gets the suggestion to check the certificate and accept it anyways.

Thank you and with best regards,
Delphine

**Comment by ShGKme** [comment]
> or windows

It should work on Windows... On the first login, it is supposed to open a native certificate approval dialog.

What Windows version do you have?

**Comment by Cate95** [comment]
I have Windows 10 on a second partition..  but my daily driver is arch linux.. Is there plans in the future for a native certificate approval dialog for the linux version? Would appreciate it alot! :)

**Comment by ShGKme** [comment]
> Is there plans in the future for a native certificate approval dialog for the linux version?

There is a plan to add a custom dialog because it is not natively supported on linux.

**Comment by ShGKme** [comment]
Duplication of: https://github.com/nextcloud/talk-desktop/issues/23
