### ISSUE TITLE
Talk desktop client for Windows

### ISSUE THREAD

**Issue by denisw2009** [nextcloud/talk-desktop#386]
I suggest to create Windows desktop client for Talk. 
It is bad that always new browser tab opens when you click to Talk icon in Nextcloud client.
I think we need stand alone application to chat in Talk

**Comment by ShGKme** [comment]
This repository is literally a standalone desktop client for Talk =D
(Also works on Windows)

Do you mean a Talk icon/notification on the Nextcloud Client should open the Nextcloud Talk desktop client?

**Comment by denisw2009** [comment]
yes. it is more useable as i think

**Comment by nickvergessen** [comment]
Feel free to install the latest preview from https://github.com/nextcloud-releases/talk-desktop/releases/
