### ISSUE TITLE
talk-desktop seems to suppress push notifications to mobile clients

### ISSUE THREAD

**Issue by markusstoll** [nextcloud/talk-desktop#403]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. I have Nextcloud 27.0.2 and latest releases for ios mobile clients for talk running. For talk-desktop, I use latest release of peview
2. If talk-desktop is not running, all mobile clients receive push notifications
3. If talk-desktop is running, all mobile clients for the same user do not receive push notifications 
4. It can be healed by closing talk-desktop and activating one mobile client again. Then push notifications are working again

### Expected behaviour
Push notification should be sent all the time and for talk-desktop as well

### Actual behaviour
see above

## Desktop client

**Talk Desktop client version:** v0.13.0 - Talk 17.1.2

**Operating system:** MacOS 

**Operating system version:** MacOs Ventura 13.6

**Microphone available:** yes

**Camera available:** yes

## Server

**Nextcloud version:** 27.0.2

**Talk app version:** 17.1.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

### Client log

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by nickvergessen** [comment]
> I have Nextcloud 27.0.2

This version is no longer supported and you should update soon.

---

Push notifications are suppressed when you are in the chat that would create the notification. But we changed this for the upcoming Talk 18 release: https://github.com/nextcloud/spreed/issues/1575#issuecomment-1727694865

**Comment by markusstoll** [comment]
Thank you, will update and get back here with feedback

**Comment by markusstoll** [comment]
Updating Nextcloud fixed the issue
