### ISSUE TITLE
`FilePicker` from `@nextcloud/dialogs` doesn't proper work

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/talk-desktop#408]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

![image](https://github.com/nextcloud/talk-desktop/assets/25978914/a6d29bb0-16ca-465d-9de8-9e5f572c1270)

**Comment by nickvergessen** [comment]
Should be fixed by https://github.com/nextcloud/spreed/pull/10855

**Comment by ShGKme** [comment]
Fixed by https://github.com/nextcloud/spreed/pull/10855
