### ISSUE TITLE
Sending update notification only once

### ISSUE THREAD

**Issue by pschopen** [nextcloud/talk-desktop#413]
When a new version is released the client doesn't stop sending notifications that an update is available. That leads to my team disabling the client because they can't upgrade themselves due to the complicated process of finding the new release on GitHub and then install it by hand despite security warnings.

I suggest to either implement an option for automated updates or sending the notification only once.

**Comment by ShGKme** [comment]
> due to the complicated process of finding the new release on GitHub and then install it by hand despite security warnings

Click on the notification opens the release page as it is said in the notification text

**Comment by nickvergessen** [comment]
But yeah a more automated update is something we plan to do later before a final release.

**Comment by pschopen** [comment]
> > due to the complicated process of finding the new release on GitHub and then install it by hand despite security warnings
> 
> Click on the notification opens the release page as it is said in the notification text

Doesn't work on windows at least. Click results in deleting the message.

Also: it doesn't have an installer and my team doesn't manage to install it without help. That could be the case for many...

However it would just help to send the notification only once.
