### ISSUE TITLE
😊 emoji rendered incorrectly

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/talk-desktop#416]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Summary
😊 emoji rendered incorrectly when reacting to messages, and also while adding to drafted message, despite indeed being the correct emoji (renders correctly in Talk Android & Talk web)

## Steps to reproduce
1. choose the 😊 emoji to react to a message, or inline in a drafted message
2. 😊 renders incorrectly

### Expected behaviour
😊 = 😊 

### Actual behaviour
😊  != 😊 

![image](https://github.com/nextcloud/talk-desktop/assets/7018928/3a769a93-902f-4fc3-a889-86e91e07dafd)

![378-137-max](https://github.com/nextcloud/talk-desktop/assets/7018928/095a0db2-7bfb-4f72-99e7-0ee767c4746e)

![Peek 2023-11-14 10-46](https://github.com/nextcloud/talk-desktop/assets/7018928/9ec327bf-390f-44ec-b526-ee275252841a)

![Peek 2023-11-14 10-48](https://github.com/nextcloud/talk-desktop/assets/7018928/c96ebf61-d630-41f4-a9df-02df9751da9c)

### Talk Desktop:

![image](https://github.com/nextcloud/talk-desktop/assets/7018928/1e1405cd-9dab-4ff0-9656-67a1be87c1ff)

### Talk via Hub/web:

![Screenshot 2023-11-14 at 10-50-33 Note to self - Talk - Nextcloud](https://github.com/nextcloud/talk-desktop/assets/7018928/6dac3c27-f2e8-4284-9825-7b24e160bb3a)

## Desktop client

----------------------------System report----------------------------
Nextcloud Talk Desktop version 0.15.0
- Built with Nextcloud Talk version 18.0.0-beta.2

Connected to:
- Server address: https://cloud.nextcloud.com
- Nextcloud Server version 28.0.0 beta 2
- Nextcloud Talk version 18.0.0-beta.2

OS: Linux 6.5.9-1-default (#1 SMP PREEMPT_DYNAMIC Wed Oct 25 10:31:37 UTC 2023 (29edc7c))
----------------------------System report----------------------------

**Talk Desktop client version:**
 v 0.15.0

**Operating system:** Windows / MacOS / Ubuntu
Linux
openSUSE Tumbleweed

**Operating system version:** Windows 11 / (In case of Linux, provide the distribution.)
openSUSE Tumbleweed

**Microphone available:** yes/no

**Camera available:** yes/no

## Server

**Nextcloud version:** (see status page: `/status.php`)
28.0.0 beta 2

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
18.0.0-beta.2

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

### Client log

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by ShGKme** [comment]
☺ = `#263a`
😊 = `#1f60a`

But for some reason, the sent message is not `#263a` but `#263a` + `#fe0f`

**Comment by ShGKme** [comment]
Oh, they are really different.
😊 != ☺️

![image](https://github.com/nextcloud/talk-desktop/assets/25978914/15adac7c-4edd-4b84-83da-326b9be62774)

**Comment by ShGKme** [comment]
The actual problem is that "smiling face" emoji (☺️) is not rendered as a beautiful picture.
"smiling face with smiling eyes" emoji (😊) is different and works fine.

They are really different emojis. When I send ☺️, I see it as an empty emoji in both Talk Desktop and Web. No matter if they where sent from Desktop or Web.

Desktop | Web
---|---
![image](https://github.com/nextcloud/talk-desktop/assets/25978914/cb6aedff-bec1-43b2-b367-ed39b357b627) | ![image](https://github.com/nextcloud/talk-desktop/assets/25978914/814d13bd-569a-4f4d-8d6d-8b095def73c6)

**Comment by ShGKme** [comment]
This is font family issue.
It is set on server as
```
system-ui, -apple-system, "Segoe UI", Roboto, Oxygen-Sans, Cantarell, Ubuntu, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"
```

As the result, `Arial` is used for emoji instead of Emoji font like `"Segoe UI Emoji"`.

We should not set all the fonts as a `font-family` for a whole document, but use emoji fonts only for a specific range of characters.

**Comment by ShGKme** [comment]
Closed, because this is a server issue. I'll open an issue on the server tomorrow.

**Comment by gerbrent** [comment]
psst... there's this handy "Transfer Issue" function meant exactly for this purpose:

![image](https://github.com/nextcloud/talk-desktop/assets/7018928/ebaa5c8c-cf4c-45c4-82d8-0617e967adf4)

**Comment by ShGKme** [comment]
> psst... there's this handy "Transfer Issue" function on the right sidebar meant exactly for this purpose:

Yes, but server has different issue template, should have screenshots from server (aka comments), and not the source of the issue is known.

**Comment by gerbrent** [comment]
more evidence in a different location, for posterity:

here, in Talk
![image](https://github.com/nextcloud/talk-desktop/assets/7018928/6fed6545-66af-4313-9c54-2a3ba2d24482)

**Comment by st3iny** [comment]
This could also be caused by using `DejaVu Sans` as the default font. It seems to overwrite some color emojis with ugly symbols. I configured my desktop environment to user another default font and now the color emojis work again.

Ref https://github.com/13rac1/emojione-color-font/issues/17
Ref https://github.com/NixOS/nixpkgs/issues/172412

**Comment by ShGKme** [comment]
Conversation is locked in flavor of https://github.com/nextcloud/server/issues/41487
