### ISSUE TITLE
Fixed version in welcome screen

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/talk-desktop#43]
https://github.com/nextcloud-gmbh/talk-desktop/blob/5b9c2edcacbad501231b7516d2396108208ab554/src/welcome/welcome.html#L130

**Comment by ShGKme** [comment]
Fixed in 
- https://github.com/nextcloud/talk-desktop/commit/63886a65ed23e6a407944323c894ccffe6b823c0
- https://github.com/nextcloud/talk-desktop/commit/6aac449ffcc865086f9676a6d3b6177e57c6885a

Not planned to add version number to the welcome screen yet.
