### ISSUE TITLE
Tray Icon on Mac has wrong color

### ISSUE THREAD

**Issue by pschopen** [nextcloud/talk-desktop#446]
Please see the image attached: All Icons are white; only Talk is black.
<img width="535" alt="grafik" src="https://github.com/nextcloud/talk-desktop/assets/65334274/6fae67a2-0728-4bc1-a6ff-74a69f2cd81f">

**Comment by ShGKme** [comment]
Could you try to restart an app and check again?

What MacOS version are you using?

**Comment by pschopen** [comment]
> Could you try to restart an app and check again?
Restartet both, App and system. No difference

> What MacOS version are you using?
Ventura 13.6

**Comment by ShGKme** [comment]
Can reproduce

**Comment by BJKle** [comment]
Same Sonoma 14.3

**Comment by ShGKme** [comment]
- Fixed by [#836](https://github.com/nextcloud/talk-desktop/pull/836)
