### ISSUE TITLE
Tray icon doesn't launch window on MacOS

### ISSUE THREAD

**Issue by moritz-t-w** [nextcloud/talk-desktop#447]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open the app
2. Click on the close button
3. Click on the tray icon

### Expected behaviour
Talk window launches

### Actual behaviour
Nothing

### Workaround
Click on the menu bar icon instead

## Desktop client

**Talk Desktop client version:** 17.1.2 (tag `v0.13.0`)

**Operating system:** MacOS

**Operating system version:** 14

**Comment by moritz-t-w** [comment]
You mean you can't reproduce on the latest version?

**Comment by ShGKme** [comment]
> You mean you can't reproduce on the latest version?

Yes

**Comment by moritz-t-w** [comment]
Ok I trust it'll work for me aswell, once the next release comes out. Thank you
