### ISSUE TITLE
Add at least one more client app.

### ISSUE THREAD

**Issue by Folaht** [nextcloud/talk-desktop#448]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add all the collab and note-taking apps.  
Starting with notes.  
Then decks, secrets, calendar, contacts, files, cospend, etc..  

**Describe alternatives you've considered**
I'm coming from nativefier which is now discontinued.  
Gluon is another option.  

**Additional context**

**Comment by nickvergessen** [comment]
This is nothing we can do

**Comment by Folaht** [comment]
Why not?  
Have the client app check if another server app is present, then add it to the client app.  
What's the difficulty?

**Comment by nickvergessen** [comment]
The effort, compatibility, update distribution, dependencies of each app, etc.
