### ISSUE TITLE
Any image dropped from the firefox browser into the conversation ends up as 0kb webp image.

### ISSUE THREAD

**Issue by Folaht** [nextcloud/talk-desktop#449]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open firefox browser.
2. Go to the image section of a search engine
3. Search for an image
4. Drag that image from your firefox browser to an NT conversation.
5. Select Send.

### Expected behaviour
![image](https://github.com/nextcloud/talk-desktop/assets/9342090/867a2cee-d51f-49ad-a40a-54c0e2b1fcc2)

### Actual behaviour
![image](https://github.com/nextcloud/talk-desktop/assets/9342090/97cca64a-fff0-4e89-9b37-4c77757bffea)

### Additional information
It doesn't matter if the image is webp or not.
What matters is if the image has been brought in via the firefox browser.  
I've tried falkon browser and that does seem to work.
I've tried a clean firefox dev browser and it has the same issue.

## Desktop client

**Talk Desktop client version:** v0.17.0 - Talk v18.0.0-rc.2

**Operating system:** Linux 

**Operating system version:** Manjaro 

**Microphone available:** n/a

**Camera available:** n/a

## Server

**Nextcloud version:** 27.1.4~ynh1

**Talk app version:** v17.1.2

**Custom Signaling server configured:** no
**Custom TURN server configured:** no
**Custom STUN server configured:** no

### Client log

Where to find this?

**Comment by ShGKme** [comment]
Cannot reproduce. For me, dragging a webp image from Firefox transfers it as a `BMP` file, but it works. Anyway, it seems to be a part of Firefox.
