### ISSUE TITLE
Cannot send picture pasted from clipboard or from file (Windows 10, Talk Desktop Client v0.20.0)

### ISSUE THREAD

**Issue by MaxRower** [nextcloud/talk-desktop#478]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. capture screen or website content into clipboard
2. paste the clipboard into the talk app
3. clicking Send in the app does not trigger any action, only hide (Ausblenden) can be used.

### Expected behaviour
The talk app should send the pasted picture.
Using Talk in Firefox or the Android App does work as expected.

### Actual behaviour
Tell us what happens instead (🖼️ screenshots often help)
Nothing

## Desktop client

**Talk Desktop client version:** v0.20.0, v0.19.0

**Operating system:** Windows

**Operating system version:** Windows 10

**Microphone available:** yes

**Camera available:** yes

## Server

**Nextcloud version:** (see status page: `/status.php`)
27.1.5.1

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
17.1.4

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes 
stun.nextcloud.com:443

## Logs

n/a

### Client log

n/a

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by MaxRower** [comment]
There are no conspicuous log entries in /index.php/settings/admin/logging

**Comment by MaxRower** [comment]
I did a wireshark capture now, and there was no traffic to the nextcloud server the moment I pressed send.

**Comment by MaxRower** [comment]
> Could you check the errors in the browser console?

Ah, do you really mean the browser console in Firefox (or whatever), when I am using the "Nextcloud Talk.exe" Program? Is there some sort of misunderstanding here?

Did a test on another Windows 10 machine on a remote location via RDP, same results.

**Comment by ShGKme** [comment]
> Ah, do you really mean the browser console in Firefox (or whatever), when I am using the \"Nextcloud Talk.exe\" Program? Is there some sort of misunderstanding here?

I apologize, I should not call it a "browser console".

You can access the console via F12 or CTRL+SHIFT+I in the Next cloud Talk Desktop client.

It is based on Electron, which uses Chromium as a UI renderer process, so the window is a kind of patched Chromium with a web-page. The main process is a Node.js process.

**Comment by MaxRower** [comment]
Ok, I do get errors there

`index.js:2 Using locale "de_AT" for language "de"
index.js:2 Language pack "de" for "talk_desktop" loaded...
index.js:2 Language pack "de" for "spreed" loaded...
JitsiStreamBackgroundEffect.worker.js?v=ae9f8e98ff9b49965055:1 [WASM] Loading model of size: 249792
JitsiStreamBackgroundEffect.worker.js?v=ae9f8e98ff9b49965055:1 INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
printChar @ JitsiStreamBackgroundEffect.worker.js?v=ae9f8e98ff9b49965055:1
index.js:2 Tribute was already bound to DIV
_attach @ index.js:2
index.js:2 Tribute was already bound to DIV
_attach @ index.js:2
index.js:2 Message to focus not found in DOM 7981
focusMessage @ index.js:2
index.js:2 TypeError: Cannot destructure property 'caption' of 'object null' as it is null.
    at o.handleUpload (index.js:2:409005)
    at click (index.js:2:407463)
    at on (index.js:2:686486)
    at o.n (index.js:2:679770)
    at on (index.js:2:686486)
    at e.$emit (index.js:2:707911)
    at click (index.js:2:1181051)
    at on (index.js:2:686486)
    at HTMLButtonElement.n (index.js:2:679770)
    at Pa.s._wrapper (index.js:2:719577)
un @ index.js:2
ln @ index.js:2
sn @ index.js:2
on @ index.js:2
n @ index.js:2
on @ index.js:2
e.$emit @ index.js:2
click @ index.js:2
on @ index.js:2
n @ index.js:2
Pa.s._wrapper @ index.js:2
`

**Comment by MaxRower** [comment]
Did the same test with the Linux client on Ubuntu 22.04, same error.

**Comment by ShGKme** [comment]
Duplication of https://github.com/nextcloud/talk-desktop/issues/473

Requires Nextcloud Talk 28 release, will be updated and released after 25 Jan.

**Comment by MaxRower** [comment]
Ok, as a workaroud, I tested the old 0.13.0 version (last based on Talk 17), and it's not an issue there.
