### ISSUE TITLE
Nextcloud Talk Windows Client does not terminate when closing the window

### ISSUE THREAD

**Issue by MaxRower** [nextcloud/talk-desktop#479]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start the Windows client
2. Close the Windows client
3. Many instances of "Nextclould Talk.exe" will continue to run forever, visible in Task Manager, only taskkill /f /im "nextcloud talk.exe" will terminate them.

### Expected behaviour
The program should terminate itself completely.

### Actual behaviour
Tell us what happens instead (🖼️ screenshots often help)
Many instances of "Nextclould Talk.exe" will continue to run forever.
Very annoying, when you get the update notification and you want to update the client over the previous version.

## Desktop client

**Talk Desktop client version:** v0.20.0 and older.

**Operating system:** Windows

**Operating system version:** Windows 10

**Microphone available:** yes

**Camera available:** yes

## Server

**Nextcloud version:** (see status page: `/status.php`)
27.1.5.1

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
17.1.4

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
no

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
yes

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
yes
stun.nextcloud.com:443

## Logs
n/a

### Client log
n/a

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by ShGKme** [comment]
> 2\. Close the Windows client

Do you close the window or the client by the system tray menu icon?

**Comment by MaxRower** [comment]
Clicking "x" in the upper right corner of the window or using Close (Alt+F4) in the system menu has the same results.
Never tried to close it using the system tray though, but that seemed to work! The system tray icon is usually hidden, didn't expect to have any mandatory features there. Works as designed?

**Comment by ShGKme** [comment]
> Works as designed?

Yes.

We can add a setting to disable minimize to tray on close, or show a notification note on the first time.

But IMO this is an expected behavior for a messenger client - minimize to tray when closed.

**Comment by MaxRower** [comment]
When I close the signal messenger this way, it will terminate fully. No system tray. So this is apperently not everyone's opinion. ;)
