### ISSUE TITLE
App doesn't run on Arch Linux, with KDE and Wayland

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/talk-desktop#48]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce

1. Open the app 

### Expected behaviour

The app opens

### Actual behaviour

Nothing happens

## Desktop client

**Talk Desktop client version:** v0.2.1

**Operating system:** Linux

**Operating system version:** Arch Linux with KDE and Wayland

## Server

n/a

## Logs

```
./Nextcloud\ Talk 
Authorization required, but no authorization protocol specified

[234173:0322/120520.630071:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[234173:0322/120520.630113:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
[1]    234173 IOT instruction (core dumped)  ./Nextcloud\ Talk
```

### Client log

n/a

cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Works for me, with latest RC.
Actually I think this was a problem with my XAuthority file.
