### ISSUE TITLE
Client pops up into foreground unwanted

### ISSUE THREAD

**Issue by postwarbreakout** [nextcloud/talk-desktop#495]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
Seen it with multiple cases:
- Change TURN or STUN config in Nextcloud Admin interface
- New update is released (seen it with 0.19 -> 0.20)

### Expected behaviour
None

### Actual behaviour
Minimized client pops up into foreground (= interrupting work) and reloads the interface (+repeatedly spams client update notification)

## Desktop client

**Talk Desktop client version:** v0.20.0

**Operating system:** Windows

**Operating system version:** Windows 11

**Microphone available:** yes

**Camera available:** yes

## Server

**Nextcloud version:** 27.1.4.1

**Talk app version:**  17.1.4

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

**Comment by ShGKme** [comment]
Thank you for the report.

It is a known issue about restarting the client on server config update: https://github.com/nextcloud/talk-desktop/issues/389

Closing as duplication to keep it in one place.
