### ISSUE TITLE
No icon in the notification on Windows 11

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/talk-desktop#51]

**Comment by nickvergessen** [comment]
Also on Ubuntu it has a default icon in the notifications
![grafik](https://user-images.githubusercontent.com/213943/226638268-1f9b3940-25de-4914-84a2-13ae5c7c88c0.png)

**Comment by fitus85** [comment]
Seems to be already fixed

Nextcloud Talk Desktop version 0.29.0 on Win 11.

![Talk_Win11_Notification](https://github.com/nextcloud/talk-desktop/assets/70263977/caec8c18-87b3-4d71-877c-a4dc0818d34b)

**Comment by ShGKme** [comment]
- Icon loading was fixed in the meanwhile
- Icon on the notification itself will be fixed by https://github.com/nextcloud/talk-desktop/pull/841
- Icon in the notification image should be removed
