### ISSUE TITLE
Disappear "\" in messages in Talk

### ISSUE THREAD

**Issue by denisw2009** [nextcloud/talk-desktop#522]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Write "\\192.168.9.1\_tems\!dfgerf\@223.zip"
2. Get "\192.168.9.1_tems!dfgerf@223.zip" in conversation
3. but if you answer (reply) to this message you will see "\\192.168.9.1\_tems\!dfgerf\@223.zip"

### Expected behaviour
Tell us what should happen
![shot](https://github.com/nextcloud/talk-desktop/assets/83764628/0e07b8b8-7467-4797-8c8e-df7d3b4d60fa)

### Actual behaviour
Tell us what happens instead (🖼️ screenshots often help)

## Desktop client

**Talk Desktop client version:** v1.0.0

**Operating system:** Windows / MacOS / Ubuntu

**Operating system version:** Windows 11 / (In case of Linux, provide the distribution.)

**Microphone available:** yes/no

**Camera available:** yes/no

## Server

**Nextcloud version:** (see status page: `/status.php`)

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

### Client log

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by ShGKme** [comment]
Cannot say what exactly caused the issue, but not reproducible anymore. Reopen if you still have this issue in the latest version.

**Comment by denisw2009** [comment]
i still have the problem. when i write "\\text" I have "\text". Nextcloud server 29.0.0, Talk 19.0.0 
![Nextcloud issue](https://github.com/nextcloud/talk-desktop/assets/83764628/177c7e13-a870-47e1-a274-fa78eb2a611e)
![Nextcloud issue1](https://github.com/nextcloud/talk-desktop/assets/83764628/d0d74b3b-6942-4083-9604-4cf8b43dfc18)
