### ISSUE TITLE
New avatar menu has wrong icon colors in dark mode

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-desktop#548]
🙈  Sorry :)

![grafik](https://github.com/nextcloud/talk-desktop/assets/213943/186545f6-0c08-457e-92b7-4b6e02c2adc6)

**Comment by ShGKme** [comment]
🥲

**Comment by ShGKme** [comment]
I cannot reproduce...

**Comment by nickvergessen** [comment]
```
----------------------------System report----------------------------
Nextcloud Talk Desktop version 0.22.0
- Built with Nextcloud Talk version 18.0.4

Connected to:
- Server address: https://cloud.nextcloud.com
- Nextcloud Server version 28.0.3
- Nextcloud Talk version 18.0.4

OS: Windows_NT 10.0.19045 (Windows 10 Pro)
----------------------------System report----------------------------
```

- Dark OS
- Nextcloud Setting "System default theme"
- User theming set to
  ![grafik](https://github.com/nextcloud/talk-desktop/assets/213943/f7b6b1df-207c-47a8-a509-1546226ef9e5)
- Color is `rgb(57, 100, 117)`

**Comment by ShGKme** [comment]
@nickvergessen still valid?

**Comment by ShGKme** [comment]
> but the status icon is missing 🙈

This one I can reproduce

**Comment by ShGKme** [comment]
> but the status icon is missing 🙈

Reproducible on Web, not a Talk Desktop bug.
