### ISSUE TITLE
Tagging a person or group in message not working

### ISSUE THREAD

**Issue by fidderr** [nextcloud/talk-desktop#560]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a conversation
2. Type @ in the `Write a message ...` box
3. Click on the person or group from the list of taggable options

### Expected behaviour
Tell us what should happen

The person or group should be tagged in the message

### Actual behaviour
Tell us what happens instead (🖼️ screenshots often help)

The person is not tagged and a console error shows up

## Desktop client

----------------------------System report----------------------------
Nextcloud Talk Desktop version 0.23.0
- Built with Nextcloud Talk version 19.0.0-beta.1

Connected to:
- Server address: xxx
- Nextcloud Server version 27.1.5
- Nextcloud Talk version 17.1.4

OS: Windows_NT 10.0.19045 (Windows 10 Pro)
----------------------------System report----------------------------

## Logs

Javascript console log when clicking the person or group from the list of taggable options:

index.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'current')
    at o.genSelectTemplate (index.js:2:1630394)
    at w.selectTemplate (index.js:2:1119553)
    at w.selectItemAtIndex (index.js:2:1113091)
    at index.js:2:1090468

**Comment by nickvergessen** [comment]
This was already fixed in Talk 19 beta2, a new desktop build is planned for today

**Comment by fidderr** [comment]
> This was already fixed in Talk 19 beta2, a new desktop build is planned for today

Thanks for the heads up. i will close the ticket.
