### ISSUE TITLE
Pretty URL for conversations link

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/talk-desktop#605]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
It would be great to have the application honour the pretty url settings, when copying the conversation link.
https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html#pretty-urls

The additional index.php token could generate confusion on users.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Similar issue for the Desktop Client: https://github.com/nextcloud/desktop/issues/3766

**Comment by nickvergessen** [comment]
Server / core should expose a capability to that clients can know.
But that is missing atm

**Comment by ShGKme** [comment]
- Fixing the issue on Talk Desktop side requires https://github.com/nextcloud/server/issues/44798

**Comment by nickvergessen** [comment]
Patch in https://github.com/nextcloud/server/issues/44799
