### ISSUE TITLE
Can't install Nextcloud Talk Desktop 0.29

### ISSUE THREAD

**Issue by blueskyfeeling** [nextcloud/talk-desktop#625]
Hi,

unfortunately, I cannot use the program and get the following error when starting. What can I do to solve the problem?

![2024-04-19 18_24_43-Error](https://github.com/nextcloud/talk-desktop/assets/22301646/e7af109e-49fd-4fa3-b293-4617edc59d5c)

Best regards

**Comment by ShGKme** [comment]
Does `v0.28.0` work for you?

**Comment by blueskyfeeling** [comment]
Unfortunately, this version doesn't work either.

It's true that I just have to start the program and not install it, right?

![2024-04-20 09_33_16-Nextcloud Talk-win32-x64-0 28 0](https://github.com/nextcloud/talk-desktop/assets/22301646/56c04b10-87e9-4140-8b77-9b900b7f607b)

**Comment by ShGKme** [comment]
> It's true that I just have to start the program and not install it, right?

Yes. But currently we cannot reproduce your issue. 

Did any previous version worked for you, or it is the first time you are trying Talk Desktop?

What Windows version do you have?

Could you open terminal in the `Nextcloud Talk` folder and run the executable from terminal for example, using `& '.\Nextcloud Talk.exe'` command if you are using the latest PowerShell. Or using `"./Nextcloud Talk.exe"` from CMD. Then send us the output of the command.

**Comment by blueskyfeeling** [comment]
Yes, a previous version has already worked. But after a update I have the current problems. Now, version 27.0 isn't possible too.

I have Windows 10 Home 64-bit.

About the last step as you mentioned - I got an error too (see attachment)

![2024-04-21 20_32_00-Window](https://github.com/nextcloud/talk-desktop/assets/22301646/7ac6dc56-db52-4b02-bc32-f57e98dba11a)

**Comment by ShGKme** [comment]
With the last screenshot - it looks like the previous run is still in processes. Try to find and end the "Nextcloud Talk" process in the task manager or restart the computer.

Then try again to run it from the terminal and check for error in the terminal itself.

**Comment by ShGKme** [comment]
Also, try to remove this folder before run: `%AppData%/Nextcloud Talk`

**Comment by blueskyfeeling** [comment]
@ShGKme 
Many, many, many thanks! The second step was the solution! Now, I can use version 0,29. I'm really happy!
