### ISSUE TITLE
Does not start on KDE Neon with X11

### ISSUE THREAD

**Issue by come-nc** [nextcloud/talk-desktop#66]
Hello,

When starting the binary from the extracted 0.2.1 archive, it exits right away with code `1`.

```
~/T/Nextcloud.Talk-linux-x64-0.2.1> uname -a
Linux […] 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
~/T/Nextcloud.Talk-linux-x64-0.2.1> cat /etc/lsb-release
DISTRIB_ID=neon
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="KDE neon 5.27"
~/T/Nextcloud.Talk-linux-x64-0.2.1> ./Nextcloud\ Talk
~/T/Nextcloud.Talk-linux-x64-0.2.1 [1]> 
```

Not sure how to get more details, starting through gdb does not show much more.

**Comment by ShGKme** [comment]
Might be related: https://github.com/nextcloud/talk-desktop/issues/48

**Comment by ShGKme** [comment]
@come-nc Could you try to run a new Linux build from the release page and check if it works on your environment?

https://github.com/nextcloud/talk-desktop/releases/tag/v0.2.1

**Comment by come-nc** [comment]
Thank you, it works now :+1:
