### ISSUE TITLE
Mic/Camera Not Working  On MacOS

### ISSUE THREAD

**Issue by jiatao99** [nextcloud/talk-desktop#661]
Installed mac version on the Sonoma. 

The meeting cannot use mic and camera, the speaker works fine.

Check the system setting/security, the nextcloud talk app now listed on either microphone or camera

I think the application should request access at the time of launch

Any work around?

**Comment by ShGKme** [comment]
- Duplication of https://github.com/nextcloud/talk-desktop/issues/50
