### ISSUE TITLE
Search word in conversations

### ISSUE THREAD

**Issue by fidderr** [nextcloud/talk-desktop#686]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

Searching for a specific word/sentence in a conversation is not possible.

**Describe the solution you'd like**

In the browser version of Talk, you can `CTRL + F`  2 times to access a windows that allows you to search for words in a conversation

**Describe alternatives you've considered**

X

**Additional context**

X

**Comment by ShGKme** [comment]
- Duplication of https://github.com/nextcloud/talk-desktop/issues/30

Search with <kbd>CTRL + F</kbd> is not a replacement, it search for text outside conversation and at the same time it doesn't search in messages in a not loaded history
