### ISSUE TITLE
What is the proper way to install on Windows and Mac?

### ISSUE THREAD

**Issue by git529** [nextcloud/talk-desktop#689]
Hello, can someone please indicate what is the recommended way to install Talk Desktop both on Windows and Mac?

I [posted on the Nexctloud Forum](https://help.nextcloud.com/t/how-to-install-nextcloud-talk-desktop/193990), but got no response.

Thanks.

**Comment by RTechSn** [comment]
Talk-Desktop is still in preview, so there is no official install packages.
See #257

**Comment by fitus85** [comment]
For the moment on Windows download the zip-Package, extract and run Nextcloud Talk.exe.
