### ISSUE TITLE
Pending invitations are not visible in Desktop client

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/talk-desktop#709]
https://github.com/nextcloud/talk-desktop/blob/ba5971a1cbe357a17019a56d8b55e748ac5984e2/src/shared/setupWebPage.js#L128-L137

`federation_enabled: false, // TODO: Missed in Capabilities. Is it a problem?`

Web uses this config to draw federation-related UI

**Comment by ShGKme** [comment]
- Fixed by https://github.com/nextcloud/talk-desktop/pull/747
