### ISSUE TITLE
Doesn't start on Linux

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/talk-desktop#71]
Arch Linux, KDE X11
No output in console.

Running strace gives the following: https://pastebin.com/mgKF023R
I see a bunch of missing files at the end, might be the cause of the problem.

This might be a duplicate of https://github.com/nextcloud/talk-desktop/issues/66 and https://github.com/nextcloud/talk-desktop/issues/48, but I think this problem is independent from the DE and display server that is used.

**Comment by ShGKme** [comment]
Thank you for providing the strace!

**Comment by ShGKme** [comment]
Works with an updated Linux built. 

The new built is created on Linux host instead of Windows host 🫥
