### ISSUE TITLE
Please enable one tick for message sent, Two tick for deliverd message , Blue tick for read the messages. 

### ISSUE THREAD

**Issue by pruthvirajkoppa** [nextcloud/talk-desktop#723]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nickvergessen** [comment]
We have:
1. Single tick for message was sent to the server
2. Double tick for message was read by everyone sharing their read status

Since there is no "delivery" kind of thing within Nextcloud, it doesn't really make sense.
