### ISSUE TITLE
Application blackout after click on the conversation

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-desktop#73]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open Nextcloud Talk.exe
2. Select Conversation
3. Application dose black

### Expected behaviour
Should load the conversation

### Actual behaviour

https://user-images.githubusercontent.com/59488153/226942952-08469fdb-7c08-4d60-89c8-13823bdf32f1.mp4

## Desktop client

**Talk Desktop client version:** v1.0.0
0.2.1
**Operating system:** Windows / MacOS / Ubuntu
Windows
**Operating system version:** Windows 11 / (In case of Linux, provide the distribution.)
Widnows 11
**Microphone available:** yes/no
Yes
**Camera available:** yes/no
Yes
## Server

**Nextcloud version:** (see status page: `/status.php`)
Nextcloud 26
**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
16.0.1
**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

### Client log

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by ShGKme** [comment]
I cannot reproduce on Windows 11

Could you please add javascript console log?

1. Open devtools with CTRL+SHIFT+S or from Menu/Window/Toggle Dev Tools
2. Console Tab
3. Clean with CTRL+L
4. Open a conversation

**Comment by AndyXheli** [comment]
Sorry so i open Nextcloud Talk desktop then i do the following 

Open devtools with CTRL+SHIFT+S or from Menu/Window/Toggle Dev Tools
Console Tab
Clean with CTRL+L
Open a conversation

**Comment by AndyXheli** [comment]
DevTools failed to load source map: Could not parse content for chrome-error://chromewebdata/preload.js.map: Unexpected end of JSON input

**Comment by AndyXheli** [comment]
I downloaded it via the website

**Comment by olmicha** [comment]
I have the same problem, there is already a new status here. Unfortunately so can not be tested :(
The OS used is Windows 11.

Thanks a lot

**Comment by lucasmarin** [comment]
Hi guys.

This error appears to be caused by the lack of a signaling server.

![image](https://user-images.githubusercontent.com/185643/228088962-00f2e772-ec2a-417e-ae05-4610fac70318.png)

**Comment by ShGKme** [comment]
Hello @lucasmarin  

Is this error related to this issue?

**Comment by AndyXheli** [comment]
Same Issue on 0.2.2 for me 😞

**Comment by lucasmarin** [comment]
> Hello @lucasmarin
> 
> Is this error related to this issue?

Yes. It's occurs after click on conversation, 

Check this video https://skybox.skymail.net.br/s/RwB54eeW93WYnGN

Regards

**Comment by fidderr** [comment]
https://user-images.githubusercontent.com/107995723/228492124-a386dbf0-34e0-4469-8097-25d3e5e891eb.mp4

Same issue on windows 10. when clicking a conversation, the screen blacks out.

**Comment by devpikachu** [comment]
@ShGKme Can confirm @lucasmarin 's statement about the lack of a signalling server. It throws a 404 when trying to access `https://<instance>/ocs/v2.php/apps/spreed/api/v3/signaling/<chat_id>`

**Comment by ShGKme** [comment]
Finally found the reason, why it shows the black screen on errors - the problem in error handling.

But still have no ideas, why it may return 404 on signaling when there are no authentication problems...

**Comment by AndyXheli** [comment]
@ShGKme I tried it on 0.3.0 and the black screen is fixed but now every time i click on a chat it just refreshes and never les me enter

**Comment by ShGKme** [comment]
I still cannot reproduce the issue.

Have this issue bneen occuring always since the app was launch for the first time, or only after some moment?

Was you session expired anytime (you was required to re-login in web browser)?

Does re-login help?

Do you have any related lines in the Nextcloud server logs?

**Comment by Pilzinsel64** [comment]
- This issue happens since the first time I launched and logged in.
- Session hasn't expired and also re-logged in the browser in between.
- Re-login does not help.
- Forge-Reloading the page does not help.
- The server logged this when the refresh triggered on Talk Client, but does not get re-logged, no matter how ofter I re-open a conversion:
![grafik](https://user-images.githubusercontent.com/23138465/231116378-887a07cf-2630-415b-899a-e0375b05d71e.png)

**Comment by AndyXheli** [comment]
> I still cannot reproduce the issue.
> 
> Have this issue bneen occuring always since the app was launch for the first time, or only after some moment?
> 
> Was you session expired anytime (you was required to re-login in web browser)?
> 
> Does re-login help?
> 
> Do you have any related lines in the Nextcloud server logs?

It's always happening for me. As soon as i open the app it shows my conversations i click on a user and then it refreshes the screen take me back i not seeing anything under logs i also did a logout and log back in and still nothing 


I'm on Nextcloud ping me there if you want and i can do a screen share so you can see

**Comment by ShGKme** [comment]
> @ShGKme Here's some errors i see under app console logs. What do you think?

404 error is most likely an authentication error in signaling, and most likely caused by invalid session in cookie.

But I still have no idea, what may cause the issue, and how to reproduce it. I'll dm you

**Comment by neter-bg** [comment]
I have the same problem under Linux (Debian 11 with LXDE). Additional to the messages in browser's Dev Tools, I recieve this messages in the terminal:
`(node:679007) electron: Failed to load URL: file:///talk_window/#/apps/spreed/not-found with error: ERR_FILE_NOT_FOUND
(Use `Nextcloud Talk --trace-warnings ...` to show where the warning was created)
[679007:0413/143101.678015:ERROR:CONSOLE(1)] "Request Network.loadNetworkResource failed. {"code":-32602,"message":"Unsupported URL scheme"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)`

It's interesting that I have two more Nextcloud servers where the desktop client works without this problem. The client is executed on the same laptop and the servers have pretty identical configurations. The only big difference is that the problematic server is hosted on Apache, but the other two are on Nginx.

**Comment by neter-bg** [comment]
> Is it on Talk Desktop v0.3.0?
It's the same on v.0.3.0 and all previous versions. The Nextcloud version is 26.0.0.
> Hmm... No differences in the `mod_rewrite` config?
I don't have mod_rewrite stuff in my configuration and the .htaccess file is not modified from the original.
