### ISSUE TITLE
Multiple accounts support

### ISSUE THREAD

**Issue by loxK** [nextcloud/talk-desktop#745]
**Is your feature request related to a problem? Please describe.**
I have accounts on multiple Nextcloud instances (work, personal and other community instances).

**Describe the solution you'd like**
Multiple accounts support in Nextcloud Talk Desktop

**Comment by ShGKme** [comment]
- Duplication of https://github.com/nextcloud/talk-desktop/issues/7

Note, currently there is a simple workaround, you can copy Nextcloud Talk folder and rename the executable to have 2 instances running simultaneously: https://github.com/nextcloud/talk-desktop?tab=readme-ov-file#-multi-account

Soon there will be a switch between accounts in one window, but without simultaneous run.
