### ISSUE TITLE
Brute force protection triggered since using the desktop client

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/talk-desktop#75]
I have more often slow requests that seem to come from brute force protection since I started using the desktop client. Though I'm not fully sure this is a but in the client, I wanted to create this ticket to start collecting some insights.

Nextcloud logs shows a lot of entries for my IP:

```
{"reqId":"CHIKQ0vqOCzOoMiXX7BJ","level":2,"time":"2023-03-22T17:13:24+00:00","remoteAddr":"77.2.30.xxx","user":"--","app":"core","method":"GET","url":"/index.php/apps/notify_push/uid","message":"Login failed: 'undefined' (Remote IP: '77.2.30.xxx')","userAgent":"--","version":"26.0.0.10","data":{"app":"core"}}
```

I couldn't see the request being issued by the talk desktop client, but the user agent seems to be empty, so might still be the case.

At least the undefined user id would match with what I see in the desktop client network log for the notify_push server web socket:

<img width="649" alt="Screenshot 2023-03-22 at 21 04 07" src="https://user-images.githubusercontent.com/3404133/227026054-f4cd711c-5c4b-4339-89e1-337212740880.png">

**Comment by ShGKme** [comment]
> but the user agent seems to be empty

It not supposed to be empty... UserAgent header is sent.

**Comment by juliushaertl** [comment]
Maybe the request is actually issued by notify_push as the url is also not the same
