### ISSUE TITLE
ClamAV reports Win.Packed.Mikey-9859574-0 in Nextcloud Talk.exe

### ISSUE THREAD

**Issue by amalg** [nextcloud/talk-desktop#757]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Download and extract [v0.35.0 - Talk v20.0.0-rc.2](https://github.com/nextcloud-releases/talk-desktop/releases/tag/v0.35.0)
2. Scan file with ClamAV
3. ClamAV reports file is infected with Win.Packed.Mikey-9859574-0 
4. File is quarantined 

## Desktop client

**Talk Desktop client version:** v0.35.0

**Operating system:** Windows 

**Operating system version:** Windows 11

**Comment by ShGKme** [comment]
This problem is on the ClamAV side. The same problem with the chromium web-browser.

https://issues.chromium.org/issues/40052576
