### ISSUE TITLE
Nextcloud talk always reports the signaling server needs upgrading. 

### ISSUE THREAD

**Issue by TheBadAdmin** [nextcloud/talk-desktop#760]
Nextcloud talk desktop 0.34 and 0.35 both dispaly: 
```
The configured signaling server needs to be updated to be compatible with this version of Talk. Please contact your administration.
```
upon clicking the first chat after starting the nextcloud desktop app, no browsers displays the same message while opening the talk room. Also, everything seems to work as expected. I think the message is wrongly displayed.

Nextcloud talk desktop: 0.35
Nextcloud server: 27.1
Nextcloud talk app: 17.1.10
Nextcloud signaling: 1.3.2 (which is the latest).

**Comment by ShGKme** [comment]
A regression from https://github.com/nextcloud/spreed/commit/2e445b0490722c77462b8599335f73c54b39b22d
