### ISSUE TITLE
Windows 11 no access to mic/cam

### ISSUE THREAD

**Issue by VaultSoldier** [nextcloud/talk-desktop#762]
## Steps to reproduce
1. Open talk settings
![image](https://github.com/user-attachments/assets/e2cb2e03-a1ff-46b1-9cd4-7a32b8766392)
![image](https://github.com/user-attachments/assets/ff6a38da-56f0-4419-b3c3-684ca45a8876)

### Expected behaviour
Nextcloud talk should ask for access?

### Actual behaviour
Error accessing devices

## Desktop client

**Talk Desktop client version:** v0.35.0

**Operating system:** Windows

**Operating system version:** Windows 11

## Server

**Nextcloud version:** 29.0.4.1

**Custom Signaling server configured:** yes v1.3.2

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

**Comment by ShGKme** [comment]
Is it classic Windows 11? Not ARM version for new Surfaces or other ARM laptops?

**Comment by VaultSoldier** [comment]
> Does relaunch help?

No

> Is it classic Windows 11? Not ARM version for new Surfaces or other ARM laptops?

Yes, standart Window 11
![image](https://github.com/user-attachments/assets/6e7e3579-e2e3-4ae1-b905-3e6b7869f60f)

**Comment by TomasPopovas** [comment]
Same for me, in web working well, desktop not working, any help with this?

**Comment by ShGKme** [comment]
@VaultSoldier Any chance you have an antivirus? If you have, could you try to disable it and check again?

**Comment by ShGKme** [comment]
Current assumption - access is block by antivirus, because the release is not signed

**Comment by VaultSoldier** [comment]
> @VaultSoldier Any chance you have an antivirus? If you have, could you try to disable it and check again?

Yes, it was antivirus
