### ISSUE TITLE
Option to minimize to tray 📥

### ISSUE THREAD

**Issue by Mywk** [nextcloud/talk-desktop#782]
It would be great if the Nextcloud Talk desktop app had an option to minimize directly to the system tray on startup.

#### Current Behavior
Currently, the app opens in a window each time it starts or minimized to the taskbar, even when added to the startup folder (e.g., `shell:startup` on Windows).

#### Desired Behavior
An option in the settings to start the app minimized to the tray would be ideal. This way we can add the app to the startup programs and have it run in the background, without having to manually minimize it every time their computer starts.

#### Benefits (Why it's needed)
- A cleaner startup experience
- Allows users to focus on their tasks without interruptions
- Ensures the app is always running and accessible

Thank you for considering this feature request!

**Comment by mokkin** [comment]
This is working, but then I don't get a notification if a message is waiting. It should be indicated in the tray then like in other applications such as Element for example.
![grafik](https://github.com/user-attachments/assets/c7fa899b-b372-48e0-87f3-a30d9cffe34b)

**Comment by ShGKme** [comment]
Having a badge/counter in the system tray icon is a separate issue.
