### ISSUE TITLE
Notify_push: invalid credentials

### ISSUE THREAD

**Issue by RTechSn** [nextcloud/talk-desktop#822]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
Hi.
I think this might be the reason for very inconsistent notification delivery. I've tried the same steps on a Chromium browser, and everything is ok there.

## Steps to reproduce
1. Have notify_push installed on the server
2. Log in into the app and open a chat
3. Open developer console, network tab
4. Search for push, find the websocket connection
5. Open messages

### Expected behaviour
No error message

### Actual behaviour
![изображение](https://github.com/user-attachments/assets/ef2e75a3-e743-4ec9-b3ae-8f2d9c1ff3fb)

## Desktop client

**Talk Desktop client version:** 0.38.0

**Operating system:** Windows

**Operating system version:** Windows 10

## Server

**Nextcloud version:**  30.0.0

**Talk app version:** 20.0.0

**Custom Signaling server configured:** No

**Custom TURN server configured:** Yes

**Custom STUN server configured:** Yes

**Comment by RTechSn** [comment]
The issue is still present on 0.39.0

**Comment by RTechSn** [comment]
I noticed that the token Nextcloud app sends through websocket is longer than token used by a web-browser.
Browser sends token that is 32 symbols long and receives "authenticated".
The app sends a token that is 106 symbols long.

**Comment by ShGKme** [comment]
Can reproduce

**Comment by ShGKme** [comment]
> I noticed that the token Nextcloud app sends through websocket is longer than token used by a web-browser.
> Browser sends token that is 32 symbols long and receives "authenticated".
> The app sends a token that is 106 symbols long.

This is expected. Browser uses `preAuth` token while client uses `user:password` authorization with app token.

But there is an issue with authorization:

`notify_push` gets an error response from the server:
```
err: Error while sending authentication request to nextcloud: Client error: 412 Precondition Failed
```

server logs:
```json
{"reqId":"Q9Xm926K6n5hROOFeMFB","level":2,"time":"2024-10-31T16:09:41+00:00","remoteAddr":"127.0.0.1","user":"shgkme","app":"no app in context","method":"GET","url":"/index.php/apps/notify_push/uid","message":"AppManger::checkAppForUser - can't decode group IDs: Your data directory is invalid.\nEnsure there is a file called \".ocdata\" in the root of the data directory.\n\nAn unhandled exception has been thrown:\nException: Environment not properly prepared. in /var/www/html/lib/private/Console/Application.php:166\nStack trace:\n#0 /var/www/html/console.php(99): OC\\Console\\Application->loadCommands(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#1 /var/www/html/occ(11): require_once('/var/www/html/c...')\n#2 {main} - json error code: 4","userAgent":"--","version":"29.0.8.1","data":[]}
```

**Comment by ShGKme** [comment]
@RTechSn What Nextcloud installation do you have? Isn't it Nextcloud Docker All-In-One (AIO)?

**Comment by ShGKme** [comment]
@RTechSn in case you are using Nextcloud AIO, could you try to run
```sh
sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ config:app:set "notify_push" enabled --value="yes"
```
and check if it helps?

**Comment by ShGKme** [comment]
- ref: https://github.com/nextcloud/all-in-one/issues/4806#issuecomment-2160283858

**Comment by RTechSn** [comment]
> [@RTechSn](https://github.com/RTechSn) What Nextcloud installation do you have? Isn't it Nextcloud Docker All-In-One (AIO)?

I have a manual install on Ubuntu 22.0.4.5 LTS, which runs Apache and. PHP-FPM. The DB is Postgres.
Push notifications are working on browsers and Android app. I can see 'authentificated' message on notify_push in Dev Tools on Chrome.



> sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ config:app:set "notify_push" enabled --value="yes"

 sudo -u www-data  php occ config:app:set "notify_push" enabled --value="yes"
Config value were not updated

**Comment by ShGKme** [comment]
> I have a manual install on Ubuntu 22.0.4.5 LTS, which runs Apache and PHP-FPM 8.3. The DB is Postgres.

Could you check for warnings/errors in logs?

> I can see 'authentificated' message on notify_push in Dev Tools on Chrome.

Web uses a different authentication method

**Comment by RTechSn** [comment]
> Could you check for warnings/errors in the server logs?

No relevant errors in Nextcloud log, or any errors happening at the time of reloading the app.
I've checked /settings/admin/logging page, any other logs i should check?

**Comment by RTechSn** [comment]
My current loglevel is 3. Should i increase it?

**Comment by RTechSn** [comment]
I've set loglevel to 1 and still got no errors.
Then i've set it to 0 and the log became too flooded by other apps.

**Comment by ShGKme** [comment]
> Then i've set it to 0 and the log became too flooded by other apps.

Try

```
cat nextcloud.log | grep notify_push | tail -n 10
```

**Comment by RTechSn** [comment]
Ok, i thing here it is.
Notice, i've not redacted user or userAgent ("--"), only IP.
`{
    "app": "no app in context",
    "exception": {
        "Code": 401,
        "CustomMessage": "Current user is not logged in",
        "Exception": "OC\\AppFramework\\Middleware\\Security\\Exceptions\\NotLoggedInException",
        "exception": {
        },
        "File": "/var/www/nextcloud/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php",
        "Line": 113,
        "Message": "Current user is not logged in",
        "message": "Current user is not logged in",
        "Trace": [
            {
                "class": "OC\\AppFramework\\Middleware\\Security\\SecurityMiddleware",
                "file": "/var/www/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php",
                "function": "beforeController",
                "line": 73,
                "type": "->"
            },
            {
                "class": "OC\\AppFramework\\Middleware\\MiddlewareDispatcher",
                "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "function": "beforeController",
                "line": 106,
                "type": "->"
            },
            {
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
                "function": "dispatch",
                "line": 161,
                "type": "->"
            },
            {
                "class": "OC\\AppFramework\\App",
                "file": "/var/www/nextcloud/lib/private/Route/Router.php",
                "function": "main",
                "line": 302,
                "type": "::"
            },
            {
                "class": "OC\\Route\\Router",
                "file": "/var/www/nextcloud/lib/base.php",
                "function": "match",
                "line": 1001,
                "type": "->"
            },
            {
                "class": "OC",
                "file": "/var/www/nextcloud/index.php",
                "function": "handleRequest",
                "line": 24,
                "type": "::"
            }
        ]
    },
    "level": 0,
    "message": "Current user is not logged in",
    "method": "GET",
    "remoteAddr": "REDACTED",
    "reqId": "35dpxetDSPn7Tzc2Rwgz",
    "time": "November 02, 2024 22:53:54",
    "url": "/index.php/apps/notify_push/uid",
    "user": "--",
    "userAgent": "--",
    "version": "30.0.1.2"
}`

**Comment by ShGKme** [comment]
@RTechSn Thanks for the log. Just in case, could you try to re-login in the Talk Desktop? Does you user name contains any special characters?

**Comment by ShGKme** [comment]
For the context:
1. Talk Desktop stores `username` and `password` from the Login flow
2. Talk Desktop uses these credentials in all HTTP requests for **Basic Authentication**
3. For notifications, it sends the same credentials via WS to `notify-push`
4. `notify-push` sends an HTTP request with **Basic Authentication** using the same credentials to `/apps/notify_push/uid`
5. `/apps/notify_push/uid` just checks the users in the credentials

If p.1, p.2, p.5 or basic authentication failed, Talk wouldn't work at all.

The only idea I have is that basic_auth in Rust doesn't encode credentials. But is should...

**Comment by ShGKme** [comment]
@icewind1991 Maybe you know in which case `/apps/notify_push/uid` from `notify_push` may fail using valid credentials (that works for other http requests with basic auth)?

**Comment by icewind1991** [comment]
`/apps/notify_push/uid` just relies on the regular nc auth logic. So there should be no reason for it to fail.

> Talk Desktop uses these credentials in all HTTP requests for Basic Authentication

Does it really do basic auth for all requests without cookies? That will be pretty bad for performance.

**Comment by ShGKme** [comment]
> > Talk Desktop uses these credentials in all HTTP requests for Basic Authentication
> 
> Does it really do basic auth for all requests without cookies? That will be pretty bad for performance.

Don't all the clients use Authorization header for authentication?

**Comment by RTechSn** [comment]
> [@RTechSn](https://github.com/RTechSn) Thanks for the log. Just in case, could you try to re-login in the Talk Desktop? Does you user name contains any special characters?

Yes, this is the first thing i've tried. 
My username is only 3 alphabet characters. I've tried to log in with another account with the same result.

I've noticed one strange thing, though. I thought it's unrelated, but there is a 404 error in the dev console, and it contains my username prepended with underscore:
![Image](https://github.com/user-attachments/assets/6b96d258-2fa4-458b-b95d-d20edd255474)

**Comment by ShGKme** [comment]
> I've noticed one strange thing, though. I thought it's unrelated, but there is a 404 error in the dev console, and it contains my username prepended with underscore:

This is expected. It is a request for a so-call backup status, and 404 is expected when you don't have it.

**Comment by RTechSn** [comment]
@ShGKme Should there be Authorization header in Get request to wss://push? 
Or credentials are transmitted inside the websocket connection?
I see this header in other requests, but not in wss.

**Comment by RTechSn** [comment]
Removing !e.credentials from this IF statement appears to solve the problem.
![Image](https://github.com/user-attachments/assets/8aa6b7a6-b3f5-41a6-8b99-c01b2168a9c6)

**Comment by RTechSn** [comment]
Also, i've logged credentials to console before and after the above post request, they are the same.
As an experiment, i've tried setting a flag for the IF statement, so only one POST request is done like so:
```
            if (window._notify_push_available = !0 && !authenticated)
            {
                const e = await i.default.post(n.notify_push.endpoints.pre_auth);
                t = e.data
                authenticated = true;
            }
```
And the second time it creates a websocket connetion, it gets "Invalid credentials". 
I think it means you have to post pre-auth every time, at least it works. But i'm no expert and perhaps there is a better solution.

**Comment by RTechSn** [comment]
@ShGKme The websocket sends a different app password from what i dumped to console from e.credentials.
If i use the password sent through the websocket message (32 characters), it's 401
If i use the dumped password (72 characters) it's 200.

**Comment by RTechSn** [comment]
I apoligize for the confustion. 
The password from the websocket was grabbed when my "patch" was applied. Without patching JS the password is the same, and it gives 200 on Curl request. 
But the app gets "Invalid credentials" with this password 🤷‍♂ 

Here is an unmodified piece of compiled JS code from the dev console
```
            if (window._notify_push_available = !0,
            !e.credentials) {
                const e = await i.default.post(n.notify_push.endpoints.pre_auth);
                t = e.data
            }
            return window._notify_push_ws = new WebSocket(n.notify_push.endpoints.websocket),
            window._notify_push_ws.onopen = () => {
                if ("object" == typeof window._notify_push_ws && window._notify_push_ws) {
                    t ? (window._notify_push_ws.send(""),
                    window._notify_push_ws.send(t)) : e.credentials && (window._notify_push_ws.send(e.credentials.username),
                    window._notify_push_ws.send(e.credentials.password));
                    for (let e in window._notify_push_listeners)
                        window._notify_push_ws.send("listen " + e)
                }
            }
```

The first IF statement is never triggered, since e.credentials already exists at the time of page loading. What i did is i removed !e.credentials clause, triggering creation of t variable. 
The next IF checks if there is t variable, and if there is, sends it through the websocket. This way i got 32 character password, and it gives 401 when used in curl request. 
BUT the websocket successfully authenticates with it. And it cannot authenticate with "the correct" password.

**Comment by ShGKme** [comment]
> Without patching JS the password is the same, and it gives 200 on Curl request.

It means that:
1. Credentials from Nextcloud Talk passed to the `notify_push` WS server are valid and `/apps/notify_push/uid` accepts them
2. When `notify_push` WS server passes the same credentials itself to `/apps/notify_push/uid` - they got rejected

Either there is a problem in `notify_push` WS server (unlikely) of there is something in their connection in your setup.

Do you have `notify_push` installed on the same server in the same network? Or in another server/docker container/another container?

Do you have the default `notify_push` config, or some specific ENV/args?

Do you have a self-signed certificate?

Could you also check the `notify_push` WS server logs? Of the `notfy_push` service, not Nextcloud instance.
You can also increase the log level with
```
php occ notify_push:log debug
```

end restore back with
```
php occ notify_push:log --restore
```

**Comment by RTechSn** [comment]
> * Credentials from Nextcloud Talk passed to the `notify_push` WS server are valid and `/apps/notify_push/uid` accepts them
> 
> * When `notify_push` WS server passes the same credentials itself to `/apps/notify_push/uid` - they got rejected

This is a crucial bit of information for me, thank you.

> Do you have `notify_push` installed on the same server in the same network? Or in another server/docker container/another container?

It runs on the same server as a Nextcloud app, on port 7867. But its accessed through a reverse proxy on my router. So the server had to go through the proxy to connect itself. 

I've added 127.0.0.1 nextcloud.myserver.com to /etc/hosts and that was it!
