### ISSUE TITLE
Feature Request: Direct File Download in Nextcloud Talk on Desktop

### ISSUE THREAD

**Issue by Morteza-j8** [nextcloud/talk-desktop#824]
Is your feature request related to a problem? Please describe. I am frustrated that when I send files through Nextcloud Talk, it opens a browser for downloading instead of allowing direct downloads or viewing within the application. This makes the process cumbersome and less efficient for users on both Linux and Windows.

Describe the solution you'd like I would like to see a feature that enables direct downloading and viewing of files shared within the Nextcloud Talk application. This would enhance user experience by allowing seamless interaction without the need to switch to a browser for file downloads.

Describe alternatives you've considered Currently, the only alternative is to use the browser to download files, which disrupts the flow of communication in Nextcloud Talk. Another option is to use other messaging platforms that allow direct file downloads, but I prefer to keep using Nextcloud for its other features.

Additional context Implementing this feature would make Nextcloud Talk a more competitive option for communication, as many users are looking for efficient file-sharing capabilities without unnecessary steps.

**Comment by ShGKme** [comment]
Makes sense
