### ISSUE TITLE
New Chat does not get added in Desktop App (Ubuntu 22.10)

### ISSUE THREAD

**Issue by l4b4r4b4b4** [nextcloud/talk-desktop#83]
**Expected behavior:**
Nextcloud desktop app should successfully update adding new chats and the other way around.

**Actual behavior:**
Nextcloud desktop app does not update to include new chats.

**Steps to reproduce:**
1. Install Nextcloud desktop app on Ubuntu 22.10 
2. Login to Nextcloud
3. Send a new chat
4. Observe that the Nextcloud desktop app does not update the new chat

**System information:**
- OS version: docker-compose on Debian 
- Desktop app version: Nextcloud 26
- Browser version (if relevant): Firefox
- Additional tools/extensions installed (if relevant): uBlock Origin / Privacy Badger

**Screenshots (if relevant):

**Comment by l4b4r4b4b4** [comment]
would've looked into it, but dont have much experience with electron and time is scarce atm... So I filed the issue...

**Comment by nickvergessen** [comment]
Totally fine, this was more "internally" for the developer picking up the task

**Comment by l4b4r4b4b4** [comment]
at least github issues work again :D
