### ISSUE TITLE
Notifications from Talk 18.0.13 not shown in macOS

### ISSUE THREAD

**Issue by andrewhotlab** [nextcloud/talk-desktop#834]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
2. open "Nextcloud Talk.app" on any supported macOS release
3. make someone send you a text a message while your app windows is minimized or not visible on screen

### Expected behaviour
Notification alert or badge should show up

### Actual behaviour
Nothing happens

## Desktop client

**Talk Desktop client version:** v0.39.0

**Operating system:** MacOS

**Operating system version:** 11.7.10 through 15.1

**Microphone available:** yes

**Camera available:** yes

## Server

**Nextcloud version:** 28.0.12

**Talk app version:** 18.0.13

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

### Client log
```
----------------------------System report----------------------------
Nextcloud Talk Desktop version 1.0.0-rc.1
- Built with Nextcloud Talk version 20.0.2

Connected to:
- Server address: https://[myserverFQDN]
- Nextcloud Server version 28.0.12
- Nextcloud Talk version 18.0.13

OS: Darwin 24.1.0 (Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:27 PDT 2024; root:xnu-11215.41.3~2/RELEASE_X86_64)
----------------------------System report----------------------------
```
</details>

**Comment by nickvergessen** [comment]
Can you try with the DMG build of Talk 1.0.0-rc.1

**Comment by andrewhotlab** [comment]
Just tried version 1.0.0-rc.1 on macOS "Sequoia" 15.1... no notification here too, and the app does not neither shows in the "Notitication" section of System Preferences! :(

**Comment by andrewhotlab** [comment]
I just tried the latest v1.0.0: notifications in macOS are still missing! :(

Honestly this makes Talk unuseful on this OS.

**Comment by SystemKeeper** [comment]
I can't reproduce on my end:
* Sequoia 15.1
* Latest Talk-Desktop
* Logged in as user "admin"
* (Entered Settings, see below)
* "Closed" the app on the top left corner with the red circle
* Sent a message from "jane"
* Waited a bit (no notify_push installed)
* Notification arrived and badge visible:

![Image](https://github.com/user-attachments/assets/2152098d-fb91-4c3f-b752-e9fa78fdfe44)

![Image](https://github.com/user-attachments/assets/68ea89d7-1eb4-456d-b635-f6b3950484fc)


> and the app does not neither shows in the "Notitication" section of System Preferences! :(

For me it shows there and then I enabled it, but it seems entering the settings in Talk Desktop triggered that for me (at least then I saw a popup about notifications). Can you check if something happens when you enter the settings?

**Comment by andrewhotlab** [comment]
I have 21 macOS here, ranging from 11.7.10 to 15.1.1 which do not receive any notification from their Nextcloud 28 instance running on a server in the same LAN... maybe the only difference from your setup is that all our users are not admins?

**Comment by SystemKeeper** [comment]
> maybe the only difference from your setup is that all our users are not admins?

That shouldn't be an issue. But I doubled checked with a different account, works:

![Image](https://github.com/user-attachments/assets/158fd9b6-198a-40c7-bdbd-2b0df428050d)

Do you see the notification when clicking on the bell in the web interface or is it missing there as well?

**Comment by andrewhotlab** [comment]
No problem with notifications via from the web browser. Only the desktop app has this issue. I'm trying to test against a Nextcloud 29 instance...

**Comment by andrewhotlab** [comment]
Aha: the same app on the same computer started to display notifications as soon as I logged to a Nextcloud 29 instance!

So the bug is related to NC 29, or likely to the 18.x branch of Talk app.

**Comment by nickvergessen** [comment]
Nothing in that regard changed.
It's more likely that you had the chat window open on that conversation or something.

**Comment by SystemKeeper** [comment]
Can you post the diagnose screen from talk-desktop and post the system report from 28 and 29?
But as @nickvergessen already said, there was no change. And again, just to be sure, I tried it:

![Image](https://github.com/user-attachments/assets/092e28c0-57db-450f-ba03-b2140ca7ae95)

**Comment by andrewhotlab** [comment]
I always followed the same procedure during tests:
1. open Talk on macOS and check all is synced;
2. click on an unused room and close the Talk window (the red "x" in macOS's app window);
3. open a browser session with another user on the same NC instance, and send a message to a room both users are members of.
No other sessions were left active for both users in the mean time.
