### ISSUE TITLE
Notification if an update is available

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-desktop#84]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Comment by nickvergessen** [comment]
Definitely planned for the long run, but won't happen for the first couple of previews.

**Comment by ShGKme** [comment]
Closed by #106
