### ISSUE TITLE
Flatpak as a primary Linux distributive

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/talk-desktop#848]

**Comment by Fuseteam** [comment]
aww was hoping to get an official snap of this

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/talk-desktop/issues/257#issue-1787384164

**Comment by ShGKme** [comment]
> aww was hoping to get an official snap of this

Each distribution has its own props and cons, and with any decision some would be disappointed.

We'll start with the selected method, and then more distributions might be added.
