### ISSUE TITLE
Add Direct Download Option for Attachments

### ISSUE THREAD

**Issue by petarmarj** [nextcloud/talk-desktop#860]
**Is your feature request related to a problem? Please describe.**
I use Talk Desktop with friends to share documents. The PDF viewer is very helpful, but there’s no direct download button for attachments. Currently, clicking on an attachment opens it in the browser, which loads the Nextcloud Files app. For ODF files, it even triggers the editor to load, increasing the time it takes to download a file.

**Describe the solution you'd like**
Add a download button in the dropdown menu (the three dots). Alternatively, add a general setting that lets users choose how to handle attachment clicks (options for download, view, or open in browser).

**Describe alternatives you've considered**
I tried changing the attachment folder setting, but it only applies to files I send to others, not the ones I receive.

**Additional context**
N/A

**Comment by nickvergessen** [comment]
Already done for the next version

**Comment by ShGKme** [comment]
- https://github.com/nextcloud/talk-desktop/issues/824
