### ISSUE TITLE
JavaScript error when switching Theme (dark/light/automatic) on MacOS

### ISSUE THREAD

**Issue by BJKle** [nextcloud/talk-desktop#878]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Install latest client on MacOS
2. Start application
3. Switch theme from dark to light or automatic

### Expected behaviour
Switch Theme and change icon color

### Actual behaviour
A JavaScript Error
Icon color is black (in both appearances)

![Image](https://github.com/user-attachments/assets/96113061-d421-4d81-9b4f-d5be7004c250)
![Image](https://github.com/user-attachments/assets/739aa457-b0fe-4c75-9084-194df96b8d84)
![Image](https://github.com/user-attachments/assets/9b3a0147-48ca-4eb1-aaf3-06472ef3f33c)

## Desktop client

**Talk Desktop client version:** 1.0.0-rc.1

**Operating system:** MacOS

**Operating system version:** Sequoia 15.1

**Microphone available:** yes

**Camera available:** yes

## Server

**Nextcloud version:** Nextcloud Hub 8 (29.0.8)

**Talk app version:** 19.0.11

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

### Client log

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by ShGKme** [comment]
Update: on Linux error is the same.

![Image](https://github.com/user-attachments/assets/8acd14a9-053a-4ece-b387-2841c2b8fa98)


On Windows it is different:

![Image](https://github.com/user-attachments/assets/ad640db9-0b58-4c2d-b6c1-4c530336b89e)

**Comment by ShGKme** [comment]
Update: only reproducible in a production build. Dev works fine...
