### ISSUE TITLE
Switch to file opens app window instead of default browser

### ISSUE THREAD

**Issue by i2h3** [nextcloud/talk-desktop#881]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have a group conversation with someone else providing a file from Nextcloud (in example a video)
2. In the three dots menu of the message, select "switch to file"

### Expected behaviour

The Nextcloud files web user interface opens in the user's default browser.

### Actual behaviour

A new app window opens with the Nextcloud files web user interface showing the file.

## Desktop client

**Talk Desktop client version:** v1.0.0-rc.1

**Operating system:** macOS

**Operating system version:** Sequoia 15.1 (24B83)

**Microphone available:** yes

**Camera available:** yes

## Server

**Nextcloud version:** 30.0.2

**Talk app version:** 20.0.2

**Custom Signaling server configured:** 🤷🏻‍♀️

**Custom TURN server configured:** 🤷🏻‍♀️

**Custom STUN server configured:** 🤷🏻‍♀️

### System Report

<details>

```
----------------------------System report----------------------------
Nextcloud Talk Desktop version 1.0.0-rc.1
- Built with Nextcloud Talk version 20.0.2

Connected to:
- Server address: https://cloud.nextcloud.com
- Nextcloud Server version 30.0.2
- Nextcloud Talk version 20.0.2

OS: Darwin 24.1.0 (Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:26 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8122)
----------------------------System report----------------------------
```

</details>

**Comment by juliusknorr** [comment]
This is also an issue when clicking on other links like github

**Comment by nickvergessen** [comment]
This only happens when you are in a "Child window" that was opened via "Cmd/Ctrl + click".
All clicks in the main window open the default browser.
Can you confirm? Otherwise it might be a new problem introduced from DMG

**Comment by ShGKme** [comment]
> 2\. In the three dots menu of the message, select "switch to file"

Do you mean "Go to file"?

![Image](https://github.com/user-attachments/assets/c1747759-822f-43c7-8f4d-c19ea96c5036)

> This only happens when you are in a "Child window" that was opened via "Cmd/Ctrl + click". All clicks in the main window open the default browser. Can you confirm? Otherwise it might be a new problem introduced from DMG

I cannot reproduce on dmg.

**Comment by juliusknorr** [comment]
> This only happens when you are in a "Child window" that was opened via "Cmd/Ctrl + click".
> All clicks in the main window open the default browser.
> Can you confirm? Otherwise it might be a new problem introduced from DMG

Indeed, can confirm.

**Comment by i2h3** [comment]
False alert, my bad. When providing a screen recording I noticed my own mistake. 🤦🏻‍♀️ The app then proceeds to open the file in the web user interface I pinned to the Dock as an app. 😅 It is very subtle but the menu bar app name gave it away. Maybe @juliusknorr has the same. Please reopen, if needed.
