### ISSUE TITLE
Menu Bar Image on macOS Only in Dark

### ISSUE THREAD

**Issue by i2h3** [nextcloud/talk-desktop#883]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have Talk running
2. Choose a background image which causes the menu bar foreground to be of light color to contrast its background

### Expected behaviour
The symbol of the menu bar extra of the Nextcloud Talk becomes light

### Actual behaviour
The symbol of the menu bar extra of the Nextcloud Talk remains dark
![Image](https://github.com/user-attachments/assets/22dc5adf-d518-4d4c-a120-d7200b84916e)

## Desktop client

**Talk Desktop client version:** v1.0.0-rc.1

**Operating system:** macOS

**Operating system version:** Sequoia 15.1 (24B83)

**Microphone available:** yes

**Camera available:** yes

## Server

**Nextcloud version:** 30.0.2

**Talk app version:** 20.0.2

**Custom Signaling server configured:** Whatever is default in AiO, doesn't matter here anyway, I guess

**Custom TURN server configured:** Whatever is default in AiO, doesn't matter here anyway, I guess

**Custom STUN server configured:** Whatever is default in AiO, doesn't matter here anyway, I guess

**Comment by ShGKme** [comment]
Just to confirm I understand the issue correctly. Do you have a **light theme** in macOS, but a **dark background image**?

**Comment by i2h3** [comment]
I have quite the default choices. See attached screenshots. The dynamic wallpaper changes during throughout the day and the derived necessary contrast by the system thus, too.

![Image](https://github.com/user-attachments/assets/68a84ae4-fbde-4e2c-98c5-1c8dd92523ea)
![Image](https://github.com/user-attachments/assets/43c2c224-cf1c-431f-9650-24d320400e32)

But I just noticed that the issue can be reproduced more simply by manually switching from a light appearance to dark mode. Then also this pops up:

![Image](https://github.com/user-attachments/assets/bafd3b05-0cb1-42be-a788-b9efbe238f0f)

The same, but for the light version, appears when switching back.

**Comment by ShGKme** [comment]
> Then also this pops up:

This is a known issue: https://github.com/nextcloud/talk-desktop/issues/878

> I have quite the default choices. See attached screenshots. The dynamic wallpaper changes during throughout the day and the derived necessary contrast by the system thus, too.

Thanks for a clarification. indeed I missed that the menu bar theme can be different from the system theme. 

Working on the fix.

**Comment by ShGKme** [comment]
Same for Linux, but I don't know how to fix this on Linux...
