### ISSUE TITLE
DMG file for ARM is not working and MacOS says it is defective.

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/talk-desktop#889]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Download [v1.0.0-rc.1 - Talk v20.0.2](https://github.com/nextcloud/talk-desktop/releases/tag/v1.0.0-rc.1)  Nextcloud.Talk-1.0.0-rc.1-arm64.dmg 
2. Mount image
3. Start Nextcloud Talk
4. Error appears

### Expected behaviour
Application should start 

### Actual behaviour

![Image](https://github.com/user-attachments/assets/05394439-0a09-406f-bccb-df8e284bed21)

## Desktop client

**Talk Desktop client version:** v1.0.0 rc2

**Operating system:** MacOS 

**Operating system version:** 15.1

**Microphone available:** yes

**Camera available:** yes

**Comment by Fuseteam** [comment]
this looks related #152

**Comment by ShGKme** [comment]
This is how macOS called an unsigned app if it is built for ARM (M-chip).

You can:

- use x64 instead, with an old open from the context menu option (the ARM version is already removed from the release)
- wait for the next release (soon)
- manually set it as "safe" by running a command in the terminal:
  ```sh
  sudo xattrs -d xattr -d com.apple.quarantine "/Applications/Nextcloud Talk.app"
  ```

**Comment by ShGKme** [comment]
> No, cannot confirm this.
> As a long term Mac user (since 2009) I have seen many dialogs and this one differs from unsigned apps.

"Since 2009" is not relevant. The first Mac with M1 (ARM) was introduced in 2020. Dialog for an unsigned app built for x64 (Intel) is different.

You can check the help link on this dialog or the quarantine attr.

**Comment by ShGKme** [comment]
@rakekniven Please, try updated `.dmg` in the release. This the same `v1.0.0-rc.1`, but universal and signed.

**Comment by mkrecek234** [comment]
@ShGKme Just installed the updated DMG. Installs and works smoothly now on ARM macOS Sequoia - and much faster than versions before.
