### ISSUE TITLE
Error message on W11 when I log on to Windows

### ISSUE THREAD

**Issue by nigelharpur** [nextcloud/talk-desktop#950]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Install Talk app v1.0.0-rc.2
2. Wait till message appears on desktop
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead (🖼️ screenshots often help)
![Image](https://github.com/user-attachments/assets/ffb66a3b-1911-470a-a30b-c208fc921c8a)
Error message appears on W11 each time I log on to Windows - click OK and then carry on, all seems to work.
## Diagnosis and logs

<details>
<summary>Diagnosis report</summary>

Insert a diagnosis report here.
### Diagnosis report

| **Nextcloud Talk Desktop**      |                                                                             |
| ------------------------------: | --------------------------------------------------------------------------- |
| **Version**                     | v1.0.0-rc.2                                                                 |
| **Built-in Talk version**       | v20.1.0-rc.2                                                                |
| **Operating system**            | Windows_NT 10.0.22631 (Windows 11 Pro)                                      |
| **Executable Path**             | C:\Users\Nigel\AppData\Local\NextcloudTalk\app-1.0.0-rc2\Nextcloud Talk.exe |
| ****Connected to****            | -                                                                           |
| **Nextcloud server version**    | 30.0.2                                                                      |
| **Nextcloud Talk version**      | 20.0.2                                                                      |
| **`notifications` app enabled** | ✅ yes                                                                       |
| **`notify_push` app enabled**   | ❌ no                                                                        |

#### Application config

```json
{
  "theme": "default",
  "systemTitleBar": false,
  "monochromeTrayIcon": false,
  "zoomFactor": 1,
  "playSoundChat": "respect-dnd",
  "playSoundCall": "respect-dnd"
}
```

It can be found in the About window (open from the menu or via <kbd>F1</kbd> and click on "Copy report" button).

</details>

<details>
<summary>Client logs</summary>

Press <kbd>Ctrl+Shift+I</kbd> (<kbd>Cmd+Option+C</kbd> on macOS) or use the context menu to open the developer tools, then go to the Console tab.

```
Insert error logs here.
```
Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
JitsiStreamBackgroundEffect.worker.js?v=fa1b69e42302a02d7a71:1 [WASM] Loading model of size: 249792
JitsiStreamBackgroundEffect.worker.js?v=fa1b69e42302a02d7a71:1 INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
printChar @ JitsiStreamBackgroundEffect.worker.js?v=fa1b69e42302a02d7a71:1
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:1 Session has been marked as inactive
index.js:1 Session has been marked as active
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:1 Session has been marked as active
index.js:1 Session has been marked as inactive
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:1 Session has been marked as inactive
index.js:1 Session has been marked as active
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:1 Session has been marked as inactive
index.js:1 Session has been marked as active
nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:1 Session has been marked as inactive
index.js:1 Session has been marked as active
index.js:2 
        
        
       GET https://nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext 404 (Not Found)
(anonymous) @ index.js:2
xhr @ index.js:2
Se @ index.js:2
Promise.then
_request @ index.js:2
request @ index.js:2
Y.forEach.qe.<computed> @ index.js:2
(anonymous) @ index.js:2
c @ index.js:2
g @ index.js:2
await in g
a @ index.js:2
i @ index.js:2
(anonymous) @ index.js:2
si @ index.js:2
m @ index.js:2
M.run @ index.js:2
Xi @ index.js:2
(anonymous) @ index.js:2
mi @ index.js:2
Promise.then
ci @ index.js:2
Mi @ index.js:2
_i @ index.js:2
M.update @ index.js:2
e.notify @ index.js:2
set @ index.js:2
o @ index.js:2
r @ index.js:2
index.js:1 Session has been marked as inactive
index.js:1 Session has been marked as active
index.js:2 
        
        
       GET https://nextcloud.orchardmusic.com/ocs/v2.php/apps/user_status/api/v1/statuses/_NigelNext 404 (Not Found)
(anonymous) @ index.js:2
xhr @ index.js:2
Se @ index.js:2
Promise.then
_request @ index.js:2
request @ index.js:2
Y.forEach.qe.<computed> @ index.js:2
(anonymous) @ index.js:2
c @ index.js:2
g @ index.js:2
await in g
a @ index.js:2
i @ index.js:2
(anonymous) @ index.js:2
si @ index.js:2
m @ index.js:2
M.run @ index.js:2
Xi @ index.js:2
(anonymous) @ index.js:2
mi @ index.js:2
Promise.then
ci @ index.js:2
Mi @ index.js:2
_i @ index.js:2
M.update @ index.js:2
e.notify @ index.js:2
set @ index.js:2
o @ index.js:2
r @ index.js:2
index.js:1 Session has been marked as inactive
</details>

**Comment by nickvergessen** [comment]
Already fixed by https://github.com/nextcloud/talk-desktop/pull/936

**Comment by nigelharpur** [comment]
Ah great, I saw 936 but wasn't sure if it was connected or not. Thanks.

On 2 December 2024 22:10:17 GMT, Joas Schilling ***@***.***> wrote:
>Already fixed by https://github.com/nextcloud/talk-desktop/pull/936
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/talk-desktop/issues/950#issuecomment-2513048422
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Live Long and Prosper
