### ISSUE TITLE
user list for @-mentions out of sync

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-desktop#953]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. I use the Desktop client the whole day, minimize it to the tray, open it again,... but it always run and never gets restarted.
2. Switching between different rooms

### Expected behaviour

When I try to @-mention people in a room the auto-completion should always list the people in the current room

### Actual behaviour

At some point the list is no longer up-to-date and only let me @-mention people from a previous room but who are not in the current room I'm typing the message.

I can't really say when it gets out of sync but most of the time quite fast after 1-2 hours of using the client and switching between rooms

## Diagnosis and logs

<details>
<summary>Diagnosis report</summary>

Insert a diagnosis report here.

### Diagnosis report

| **Nextcloud Talk Desktop**      |                                                                                    |
| ------------------------------: | ---------------------------------------------------------------------------------- |
| **Version**                     | v1.0.0-rc.2                                                                        |
| **Built-in Talk version**       | v20.1.0-rc.2                                                                       |
| **Operating system**            | Linux 6.11.8-200.fc40.x86_64 (#1 SMP PREEMPT_DYNAMIC Thu Nov 14 20:38:18 UTC 2024) |
| **Executable Path**             | /app/lib/com.nextcloud.talk/Nextcloud Talk                                         |
| **Using Wayland**               | ✅ yes                                                                              |
| ****Connected to****            | -                                                                                  |
| **Nextcloud server version**    | 30.0.3 RC1                                                                         |
| **Nextcloud Talk version**      | 20.1.0-rc.3                                                                        |
| **`notifications` app enabled** | ✅ yes                                                                              |
| **`notify_push` app enabled**   | ✅ yes                                                                              |

#### Application config

```json
{
  "theme": "default",
  "systemTitleBar": true,
  "monochromeTrayIcon": false,
  "zoomFactor": 1,
  "playSoundChat": "respect-dnd",
  "playSoundCall": "respect-dnd"
}
```

</details>

<details>
<summary>Client logs</summary>

Press <kbd>Ctrl+Shift+I</kbd> (<kbd>Cmd+Option+C</kbd> on macOS) or use the context menu to open the developer tools, then go to the Console tab.

It shows quite some 404, not sure if they are relevant

![Image](https://github.com/user-attachments/assets/509fcf8e-d340-4288-ac81-770c5c4cb486)

</details>

**Comment by nickvergessen** [comment]
- Fixed in 20.1.0-rc.3 which is not yet available as desktop client: https://github.com/nextcloud/spreed/pull/13870
