### ISSUE TITLE
Error while setting default media state when clicking on toggle to turn off camera and microphone by default when joining a call

### ISSUE THREAD

**Issue by git529** [nextcloud/talk-desktop#957]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Install latest Nextcloud Talk Desktop app (v1.0.0 - Talk v20.1.0) on MacOS 18.1 (Apple Silicon)
2. Open app then Settings
3. Toggle on option to "Turn off camera and microphone by default when joining a call"

### Expected behaviour
Tuggle should go from off position to on position

### Actual behaviour
Error popup saying: "Error while setting default media state"

![Image](https://github.com/user-attachments/assets/86246be0-db3c-410e-8137-7a59b2fe9036)

## Diagnosis and logs

<details>
<summary>Diagnosis report</summary>

### Diagnosis report

| **Nextcloud Talk Desktop**      |                                                                                                                       |
| ------------------------------: | --------------------------------------------------------------------------------------------------------------------- |
| **Version**                     | v1.0.0                                                                                                                |
| **Built-in Talk version**       | v20.1.0                                                                                                               |
| **Operating system**            | Darwin 24.1.0 (Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020) |
| **Executable Path**             | /Applications/Nextcloud Talk.app/Contents/MacOS/Nextcloud Talk                                                        |
| ****Connected to****            | -                                                                                                                     |
| **Nextcloud server version**    | 30.0.1 RC1                                                                                                            |
| **Nextcloud Talk version**      | 20.0.2                                                                                                                |
| **`notifications` app enabled** | ✅ yes                                                                                                                 |
| **`notify_push` app enabled**   | ✅ yes                                                                                                                 |

#### Application config

```json
{
  "theme": "default",
  "systemTitleBar": false,
  "monochromeTrayIcon": false,
  "zoomFactor": 1,
  "playSoundChat": "respect-dnd",
  "playSoundCall": "respect-dnd",
  "enableCallbox": "respect-dnd"
}
```

</details>

<details>
<summary>Client logs</summary>

Press <kbd>Ctrl+Shift+I</kbd> (<kbd>Cmd+Option+C</kbd> on macOS) or use the context menu to open the developer tools, then go to the Console tab.

 server responded with a status of 400 ()
calls_start_without_media:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
index.js:2 Storing device selection in the browser storage:  videoInputId null
calls_start_without_media:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
2index.js:2 Conversations were saved to BrowserStorage. Estimated object size: 17.45 kB
_fc0b725b-d896-48a7-ab5d-ac3022e0f873:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:2 Conversations were saved to BrowserStorag

```
Insert error logs here.
```

</details>

**Comment by nickvergessen** [comment]
It should work after updating the Nextcloud Talk server so to 20.1
Seems we missed to wrap the toggle with a feature flag

**Comment by nickvergessen** [comment]
@DorraJaouad can you wrap the settings option with a check if the `config => call => start-without-media (local)` capability is there?

**Comment by Antreesy** [comment]
To follow up on that: we discussed in the office that features a-like this one (pure frontend, server is only needed for cross-device support) e.g.:
- call without media
- blur background
- compact conversations list

can be supported with Desktop client with old servers, but keep it in browser storage
