### ISSUE TITLE
Incoming call is shown for old notifications

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/talk-desktop#961]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have an old/missed call notification in your notifications
2. Have enough "new" notifications, that the call notification is not received on the `/notifications` endpoint
3. Make sure that the call notification gets back to the first 25 elements and therefore returned by the server (it's not happening all the time, not sure if we track the last notification id or the like)

### Expected behaviour
No call notification should be triggered by an old call notification

### Actual behaviour
![Image](https://github.com/user-attachments/assets/2956618f-b018-40dc-88b5-8363baec39e6)

![Image](https://github.com/user-attachments/assets/0a18e77e-6200-4a1b-b20c-d66620370fd6)

## Diagnosis and logs

<details>
<summary>Diagnosis report</summary>

### Diagnosis report

| **Nextcloud Talk Desktop**      |                                                                                                                       |
| ------------------------------: | --------------------------------------------------------------------------------------------------------------------- |
| **Version**                     | v1.0.0                                                                                                                |
| **Built-in Talk version**       | v20.1.0                                                                                                               |
| **Operating system**            | Darwin 24.1.0 (Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000) |
| **Executable Path**             | /Applications/Nextcloud Talk.app/Contents/MacOS/Nextcloud Talk                                                        |
| ****Connected to****            | -                                                                                                                     |
| **Nextcloud server version**    | 31.0.0 dev                                                                                                            |
| **Nextcloud Talk version**      | 21.0.0-dev.3                                                                                                          |
| **`notifications` app enabled** | ✅ yes                                                                                                                 |
| **`notify_push` app enabled**   | ✅ yes                                                                                                                 |

#### Application config

```json
{
  "theme": "default",
  "systemTitleBar": false,
  "monochromeTrayIcon": true,
  "zoomFactor": 1,
  "playSoundChat": "respect-dnd",
  "playSoundCall": "respect-dnd",
  "enableCallbox": "respect-dnd"
}
```

</details>

**Comment by nickvergessen** [comment]
Web fix back then https://github.com/nextcloud/notifications/pull/1943

**Comment by nickvergessen** [comment]
- While https://github.com/nextcloud/talk-desktop/pull/964 fixes the call windows, it would still play the sound for chat messages (and missed calls?) So the "remember the last threshhold" is still required
