### ISSUE TITLE
Delayed notifications

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-desktop#980]
It happens to me that the desktop client v1.0 on Linux sometimes send shows old notification. For example, it started ringing one day after the call took place. Same happens sometimes for chat notifications.

I'm not sure if this is a desktop client issue as such or more a issue of the server side push?

A idea how this could be mitigated: Would it be possible that when the client receives a push notification it first double check: is the call still ongoing? If yes, show the notification if not skip it. Is the chat message still marked as unread? If yes, show the notification, if not skip it.

**Comment by Antreesy** [comment]
Hi!

It was fixed recently in https://github.com/nextcloud/talk-desktop/pull/967, waiting for release
